// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartWatch4G.Infrastructure.Persistence;

#nullable disable

namespace SmartWatch4G.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322131858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.AccDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<string>("XValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DataTime");

                    b.ToTable("AccDataRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.AlarmEventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AlarmType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Value1")
                        .HasColumnType("float");

                    b.Property<double?>("Value2")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "AlarmType", "AlarmTime");

                    b.ToTable("AlarmEventRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.CallLogRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmLat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmLon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CallStatus")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSosAlarm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "IsSosAlarm");

                    b.ToTable("CallLogRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.DeviceInfoRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BandDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunicationMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Imsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetOperator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetworkStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefSignal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sim1CellId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sim1IccId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sim1NetAdhere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WatchEvent")
                        .HasColumnType("int");

                    b.Property<string>("WearingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceInfoRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.DeviceStatusRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EventTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ReceivedAt");

                    b.ToTable("DeviceStatusRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.EcgDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RawDataBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DataTime");

                    b.ToTable("EcgDataRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.GnssTrackRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<float?>("CaloriesKcal")
                        .HasColumnType("real");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<float?>("DistanceMetres")
                        .HasColumnType("real");

                    b.Property<int>("GpsType")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rssi")
                        .HasColumnType("int");

                    b.Property<long?>("Steps")
                        .HasColumnType("bigint");

                    b.Property<string>("TrackTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "TrackTime");

                    b.ToTable("GnssTrackRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.HealthDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("ActivityState")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActivityType")
                        .HasColumnType("bigint");

                    b.Property<long?>("AvgHeartRate")
                        .HasColumnType("bigint");

                    b.Property<long?>("AvgSpo2")
                        .HasColumnType("bigint");

                    b.Property<float?>("AxillaryTemp")
                        .HasColumnType("real");

                    b.Property<int?>("BiozR")
                        .HasColumnType("int");

                    b.Property<int?>("BiozX")
                        .HasColumnType("int");

                    b.Property<float?>("BloodPotassium")
                        .HasColumnType("real");

                    b.Property<float?>("BloodSugar")
                        .HasColumnType("real");

                    b.Property<float?>("Bmi")
                        .HasColumnType("real");

                    b.Property<float?>("BodyFat")
                        .HasColumnType("real");

                    b.Property<long?>("BpBpm")
                        .HasColumnType("bigint");

                    b.Property<float?>("CaloriesKcal")
                        .HasColumnType("real");

                    b.Property<string>("DataTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("Dbp")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<float?>("DistanceMetres")
                        .HasColumnType("real");

                    b.Property<float?>("EnvTemp")
                        .HasColumnType("real");

                    b.Property<float?>("EstimatedTemp")
                        .HasColumnType("real");

                    b.Property<int?>("Fatigue")
                        .HasColumnType("int");

                    b.Property<double?>("HrvMean")
                        .HasColumnType("float");

                    b.Property<double?>("HrvPnn50")
                        .HasColumnType("float");

                    b.Property<double?>("HrvRmssd")
                        .HasColumnType("float");

                    b.Property<double?>("HrvSdnn")
                        .HasColumnType("float");

                    b.Property<float?>("MatressHumidity")
                        .HasColumnType("real");

                    b.Property<float?>("MatressTemperature")
                        .HasColumnType("real");

                    b.Property<long?>("MaxHeartRate")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaxSpo2")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinHeartRate")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinSpo2")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Sbp")
                        .HasColumnType("bigint");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<float?>("ShellTemp")
                        .HasColumnType("real");

                    b.Property<string>("SleepDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Steps")
                        .HasColumnType("bigint");

                    b.Property<int?>("TemperatureIsValid")
                        .HasColumnType("int");

                    b.Property<long?>("UricAcid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DataTime");

                    b.ToTable("HealthDataRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.RriDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RriValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DataTime");

                    b.ToTable("RriDataRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.SleepDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<string>("SleepDate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SleepJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "SleepDate", "Seq");

                    b.ToTable("SleepDataRecords");
                });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.Spo2DataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int>("Perfusion")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Spo2")
                        .HasColumnType("int");

                    b.Property<int>("Touch")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DataTime");

                    b.ToTable("Spo2DataRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
