// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ACCelerometer_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ACCelerometer_data.proto</summary>
public static partial class ACCelerometerDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ACCelerometer_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ACCelerometerDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhBQ0NlbGVyb21ldGVyX2RhdGEucHJvdG8aE3JlYWx0aW1lX2RhdGEucHJv",
          "dG8idgoQSGlzQUNDZWxlcm9tZXRlchIdCgp0aW1lX3N0YW1wGAEgAigLMgku",
          "RGF0ZVRpbWUSFgoOYWNjX2RhdGFfY291bnQYAiACKAcSDQoFYWNjX3gYAyAC",
          "KAwSDQoFYWNjX3kYBCACKAwSDQoFYWNjX3oYBSACKAxCCVoHLi9pd293bg=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HisACCelerometer), global::HisACCelerometer.Parser, new[]{ "TimeStamp", "AccDataCount", "AccX", "AccY", "AccZ" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HisACCelerometer : pb::IMessage<HisACCelerometer> {
  private static readonly pb::MessageParser<HisACCelerometer> _parser = new pb::MessageParser<HisACCelerometer>(() => new HisACCelerometer());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisACCelerometer> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ACCelerometerDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisACCelerometer() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisACCelerometer(HisACCelerometer other) : this() {
    _hasBits0 = other._hasBits0;
    timeStamp_ = other.HasTimeStamp ? other.timeStamp_.Clone() : null;
    accDataCount_ = other.accDataCount_;
    accX_ = other.accX_;
    accY_ = other.accY_;
    accZ_ = other.accZ_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisACCelerometer Clone() {
    return new HisACCelerometer(this);
  }

  /// <summary>Field number for the "time_stamp" field.</summary>
  public const int TimeStampFieldNumber = 1;
  private global::DateTime timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the time_stamp field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTimeStamp {
    get { return timeStamp_ != null; }
  }
  /// <summary>Clears the value of the time_stamp field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimeStamp() {
    timeStamp_ = null;
  }

  /// <summary>Field number for the "acc_data_count" field.</summary>
  public const int AccDataCountFieldNumber = 2;
  private readonly static uint AccDataCountDefaultValue = 0;

  private uint accDataCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint AccDataCount {
    get { if ((_hasBits0 & 1) != 0) { return accDataCount_; } else { return AccDataCountDefaultValue; } }
    set {
      _hasBits0 |= 1;
      accDataCount_ = value;
    }
  }
  /// <summary>Gets whether the "acc_data_count" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAccDataCount {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "acc_data_count" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAccDataCount() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "acc_x" field.</summary>
  public const int AccXFieldNumber = 3;
  private readonly static pb::ByteString AccXDefaultValue = pb::ByteString.Empty;

  private pb::ByteString accX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString AccX {
    get { return accX_ ?? AccXDefaultValue; }
    set {
      accX_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "acc_x" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAccX {
    get { return accX_ != null; }
  }
  /// <summary>Clears the value of the "acc_x" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAccX() {
    accX_ = null;
  }

  /// <summary>Field number for the "acc_y" field.</summary>
  public const int AccYFieldNumber = 4;
  private readonly static pb::ByteString AccYDefaultValue = pb::ByteString.Empty;

  private pb::ByteString accY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString AccY {
    get { return accY_ ?? AccYDefaultValue; }
    set {
      accY_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "acc_y" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAccY {
    get { return accY_ != null; }
  }
  /// <summary>Clears the value of the "acc_y" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAccY() {
    accY_ = null;
  }

  /// <summary>Field number for the "acc_z" field.</summary>
  public const int AccZFieldNumber = 5;
  private readonly static pb::ByteString AccZDefaultValue = pb::ByteString.Empty;

  private pb::ByteString accZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString AccZ {
    get { return accZ_ ?? AccZDefaultValue; }
    set {
      accZ_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "acc_z" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAccZ {
    get { return accZ_ != null; }
  }
  /// <summary>Clears the value of the "acc_z" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAccZ() {
    accZ_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisACCelerometer);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisACCelerometer other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
    if (AccDataCount != other.AccDataCount) return false;
    if (AccX != other.AccX) return false;
    if (AccY != other.AccY) return false;
    if (AccZ != other.AccZ) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    if (HasAccDataCount) hash ^= AccDataCount.GetHashCode();
    if (HasAccX) hash ^= AccX.GetHashCode();
    if (HasAccY) hash ^= AccY.GetHashCode();
    if (HasAccZ) hash ^= AccZ.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTimeStamp) {
      output.WriteRawTag(10);
      output.WriteMessage(TimeStamp);
    }
    if (HasAccDataCount) {
      output.WriteRawTag(21);
      output.WriteFixed32(AccDataCount);
    }
    if (HasAccX) {
      output.WriteRawTag(26);
      output.WriteBytes(AccX);
    }
    if (HasAccY) {
      output.WriteRawTag(34);
      output.WriteBytes(AccY);
    }
    if (HasAccZ) {
      output.WriteRawTag(42);
      output.WriteBytes(AccZ);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
    }
    if (HasAccDataCount) {
      size += 1 + 4;
    }
    if (HasAccX) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(AccX);
    }
    if (HasAccY) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(AccY);
    }
    if (HasAccZ) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(AccZ);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisACCelerometer other) {
    if (other == null) {
      return;
    }
    if (other.HasTimeStamp) {
      if (!HasTimeStamp) {
        TimeStamp = new global::DateTime();
      }
      TimeStamp.MergeFrom(other.TimeStamp);
    }
    if (other.HasAccDataCount) {
      AccDataCount = other.AccDataCount;
    }
    if (other.HasAccX) {
      AccX = other.AccX;
    }
    if (other.HasAccY) {
      AccY = other.AccY;
    }
    if (other.HasAccZ) {
      AccZ = other.AccZ;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTimeStamp) {
            TimeStamp = new global::DateTime();
          }
          input.ReadMessage(TimeStamp);
          break;
        }
        case 21: {
          AccDataCount = input.ReadFixed32();
          break;
        }
        case 26: {
          AccX = input.ReadBytes();
          break;
        }
        case 34: {
          AccY = input.ReadBytes();
          break;
        }
        case 42: {
          AccZ = input.ReadBytes();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
