// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: his_multi_leads_ecg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from his_multi_leads_ecg.proto</summary>
public static partial class HisMultiLeadsEcgReflection {

  #region Descriptor
  /// <summary>File descriptor for his_multi_leads_ecg.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HisMultiLeadsEcgReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChloaXNfbXVsdGlfbGVhZHNfZWNnLnByb3RvGhNyZWFsdGltZV9kYXRhLnBy",
          "b3RvIoEBChRIaXNEYXRhTXVsdGlMZWFkc0VDRxIdCgp0aW1lX3N0YW1wGAEg",
          "AigLMgkuRGF0ZVRpbWUSGgoSTnVtYmVyX29mX2NoYW5uZWxzGAIgAigHEhwK",
          "FFNpbmdsZV9kYXRhX2J5dGVfbGVuGAMgAigHEhAKCHJhd19kYXRhGAQgAigM",
          "QglaBy4vaXdvd24="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataMultiLeadsECG), global::HisDataMultiLeadsECG.Parser, new[]{ "TimeStamp", "NumberOfChannels", "SingleDataByteLen", "RawData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HisDataMultiLeadsECG : pb::IMessage<HisDataMultiLeadsECG> {
  private static readonly pb::MessageParser<HisDataMultiLeadsECG> _parser = new pb::MessageParser<HisDataMultiLeadsECG>(() => new HisDataMultiLeadsECG());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataMultiLeadsECG> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisMultiLeadsEcgReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataMultiLeadsECG() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataMultiLeadsECG(HisDataMultiLeadsECG other) : this() {
    _hasBits0 = other._hasBits0;
    timeStamp_ = other.HasTimeStamp ? other.timeStamp_.Clone() : null;
    numberOfChannels_ = other.numberOfChannels_;
    singleDataByteLen_ = other.singleDataByteLen_;
    rawData_ = other.rawData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataMultiLeadsECG Clone() {
    return new HisDataMultiLeadsECG(this);
  }

  /// <summary>Field number for the "time_stamp" field.</summary>
  public const int TimeStampFieldNumber = 1;
  private global::DateTime timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the time_stamp field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTimeStamp {
    get { return timeStamp_ != null; }
  }
  /// <summary>Clears the value of the time_stamp field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimeStamp() {
    timeStamp_ = null;
  }

  /// <summary>Field number for the "Number_of_channels" field.</summary>
  public const int NumberOfChannelsFieldNumber = 2;
  private readonly static uint NumberOfChannelsDefaultValue = 0;

  private uint numberOfChannels_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint NumberOfChannels {
    get { if ((_hasBits0 & 1) != 0) { return numberOfChannels_; } else { return NumberOfChannelsDefaultValue; } }
    set {
      _hasBits0 |= 1;
      numberOfChannels_ = value;
    }
  }
  /// <summary>Gets whether the "Number_of_channels" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasNumberOfChannels {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "Number_of_channels" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearNumberOfChannels() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "Single_data_byte_len" field.</summary>
  public const int SingleDataByteLenFieldNumber = 3;
  private readonly static uint SingleDataByteLenDefaultValue = 0;

  private uint singleDataByteLen_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint SingleDataByteLen {
    get { if ((_hasBits0 & 2) != 0) { return singleDataByteLen_; } else { return SingleDataByteLenDefaultValue; } }
    set {
      _hasBits0 |= 2;
      singleDataByteLen_ = value;
    }
  }
  /// <summary>Gets whether the "Single_data_byte_len" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSingleDataByteLen {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "Single_data_byte_len" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSingleDataByteLen() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "raw_data" field.</summary>
  public const int RawDataFieldNumber = 4;
  private readonly static pb::ByteString RawDataDefaultValue = pb::ByteString.Empty;

  private pb::ByteString rawData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString RawData {
    get { return rawData_ ?? RawDataDefaultValue; }
    set {
      rawData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "raw_data" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRawData {
    get { return rawData_ != null; }
  }
  /// <summary>Clears the value of the "raw_data" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRawData() {
    rawData_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataMultiLeadsECG);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataMultiLeadsECG other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
    if (NumberOfChannels != other.NumberOfChannels) return false;
    if (SingleDataByteLen != other.SingleDataByteLen) return false;
    if (RawData != other.RawData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    if (HasNumberOfChannels) hash ^= NumberOfChannels.GetHashCode();
    if (HasSingleDataByteLen) hash ^= SingleDataByteLen.GetHashCode();
    if (HasRawData) hash ^= RawData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTimeStamp) {
      output.WriteRawTag(10);
      output.WriteMessage(TimeStamp);
    }
    if (HasNumberOfChannels) {
      output.WriteRawTag(21);
      output.WriteFixed32(NumberOfChannels);
    }
    if (HasSingleDataByteLen) {
      output.WriteRawTag(29);
      output.WriteFixed32(SingleDataByteLen);
    }
    if (HasRawData) {
      output.WriteRawTag(34);
      output.WriteBytes(RawData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
    }
    if (HasNumberOfChannels) {
      size += 1 + 4;
    }
    if (HasSingleDataByteLen) {
      size += 1 + 4;
    }
    if (HasRawData) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(RawData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataMultiLeadsECG other) {
    if (other == null) {
      return;
    }
    if (other.HasTimeStamp) {
      if (!HasTimeStamp) {
        TimeStamp = new global::DateTime();
      }
      TimeStamp.MergeFrom(other.TimeStamp);
    }
    if (other.HasNumberOfChannels) {
      NumberOfChannels = other.NumberOfChannels;
    }
    if (other.HasSingleDataByteLen) {
      SingleDataByteLen = other.SingleDataByteLen;
    }
    if (other.HasRawData) {
      RawData = other.RawData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTimeStamp) {
            TimeStamp = new global::DateTime();
          }
          input.ReadMessage(TimeStamp);
          break;
        }
        case 21: {
          NumberOfChannels = input.ReadFixed32();
          break;
        }
        case 29: {
          SingleDataByteLen = input.ReadFixed32();
          break;
        }
        case 34: {
          RawData = input.ReadBytes();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
