// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: his_swim_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from his_swim_data.proto</summary>
public static partial class HisSwimDataReflection {

  #region Descriptor
  /// <summary>File descriptor for his_swim_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HisSwimDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNoaXNfc3dpbV9kYXRhLnByb3RvGhNyZWFsdGltZV9kYXRhLnByb3RvIiwK",
          "CVNlbnNvclZlYxIJCgF4GAEgAigHEgkKAXkYAiACKAcSCQoBehgDIAIoByJt",
          "CgtIaXNEYXRhU3dpbRIdCgp0aW1lX3N0YW1wGAEgAigLMgkuRGF0ZVRpbWUS",
          "IQoNYWNjX2d5cm9fZGF0YRgCIAMoCzIKLlNlbnNvclZlYxIcCghtYWdfZGF0",
          "YRgDIAIoCzIKLlNlbnNvclZlY0IJWgcuL2l3b3du"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SensorVec), global::SensorVec.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataSwim), global::HisDataSwim.Parser, new[]{ "TimeStamp", "AccGyroData", "MagData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SensorVec : pb::IMessage<SensorVec> {
  private static readonly pb::MessageParser<SensorVec> _parser = new pb::MessageParser<SensorVec>(() => new SensorVec());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SensorVec> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisSwimDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SensorVec() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SensorVec(SensorVec other) : this() {
    _hasBits0 = other._hasBits0;
    x_ = other.x_;
    y_ = other.y_;
    z_ = other.z_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SensorVec Clone() {
    return new SensorVec(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private readonly static uint XDefaultValue = 0;

  private uint x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint X {
    get { if ((_hasBits0 & 1) != 0) { return x_; } else { return XDefaultValue; } }
    set {
      _hasBits0 |= 1;
      x_ = value;
    }
  }
  /// <summary>Gets whether the "x" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasX {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "x" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearX() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private readonly static uint YDefaultValue = 0;

  private uint y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Y {
    get { if ((_hasBits0 & 2) != 0) { return y_; } else { return YDefaultValue; } }
    set {
      _hasBits0 |= 2;
      y_ = value;
    }
  }
  /// <summary>Gets whether the "y" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasY {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "y" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearY() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "z" field.</summary>
  public const int ZFieldNumber = 3;
  private readonly static uint ZDefaultValue = 0;

  private uint z_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Z {
    get { if ((_hasBits0 & 4) != 0) { return z_; } else { return ZDefaultValue; } }
    set {
      _hasBits0 |= 4;
      z_ = value;
    }
  }
  /// <summary>Gets whether the "z" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasZ {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "z" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearZ() {
    _hasBits0 &= ~4;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SensorVec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SensorVec other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (X != other.X) return false;
    if (Y != other.Y) return false;
    if (Z != other.Z) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasX) hash ^= X.GetHashCode();
    if (HasY) hash ^= Y.GetHashCode();
    if (HasZ) hash ^= Z.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasX) {
      output.WriteRawTag(13);
      output.WriteFixed32(X);
    }
    if (HasY) {
      output.WriteRawTag(21);
      output.WriteFixed32(Y);
    }
    if (HasZ) {
      output.WriteRawTag(29);
      output.WriteFixed32(Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasX) {
      size += 1 + 4;
    }
    if (HasY) {
      size += 1 + 4;
    }
    if (HasZ) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SensorVec other) {
    if (other == null) {
      return;
    }
    if (other.HasX) {
      X = other.X;
    }
    if (other.HasY) {
      Y = other.Y;
    }
    if (other.HasZ) {
      Z = other.Z;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          X = input.ReadFixed32();
          break;
        }
        case 21: {
          Y = input.ReadFixed32();
          break;
        }
        case 29: {
          Z = input.ReadFixed32();
          break;
        }
      }
    }
  }

}

public sealed partial class HisDataSwim : pb::IMessage<HisDataSwim> {
  private static readonly pb::MessageParser<HisDataSwim> _parser = new pb::MessageParser<HisDataSwim>(() => new HisDataSwim());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataSwim> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisSwimDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataSwim() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataSwim(HisDataSwim other) : this() {
    timeStamp_ = other.HasTimeStamp ? other.timeStamp_.Clone() : null;
    accGyroData_ = other.accGyroData_.Clone();
    magData_ = other.HasMagData ? other.magData_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataSwim Clone() {
    return new HisDataSwim(this);
  }

  /// <summary>Field number for the "time_stamp" field.</summary>
  public const int TimeStampFieldNumber = 1;
  private global::DateTime timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the time_stamp field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTimeStamp {
    get { return timeStamp_ != null; }
  }
  /// <summary>Clears the value of the time_stamp field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimeStamp() {
    timeStamp_ = null;
  }

  /// <summary>Field number for the "acc_gyro_data" field.</summary>
  public const int AccGyroDataFieldNumber = 2;
  private static readonly pb::FieldCodec<global::SensorVec> _repeated_accGyroData_codec
      = pb::FieldCodec.ForMessage(18, global::SensorVec.Parser);
  private readonly pbc::RepeatedField<global::SensorVec> accGyroData_ = new pbc::RepeatedField<global::SensorVec>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::SensorVec> AccGyroData {
    get { return accGyroData_; }
  }

  /// <summary>Field number for the "mag_data" field.</summary>
  public const int MagDataFieldNumber = 3;
  private global::SensorVec magData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::SensorVec MagData {
    get { return magData_; }
    set {
      magData_ = value;
    }
  }
  /// <summary>Gets whether the mag_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMagData {
    get { return magData_ != null; }
  }
  /// <summary>Clears the value of the mag_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMagData() {
    magData_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataSwim);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataSwim other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
    if(!accGyroData_.Equals(other.accGyroData_)) return false;
    if (!object.Equals(MagData, other.MagData)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    hash ^= accGyroData_.GetHashCode();
    if (HasMagData) hash ^= MagData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTimeStamp) {
      output.WriteRawTag(10);
      output.WriteMessage(TimeStamp);
    }
    accGyroData_.WriteTo(output, _repeated_accGyroData_codec);
    if (HasMagData) {
      output.WriteRawTag(26);
      output.WriteMessage(MagData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
    }
    size += accGyroData_.CalculateSize(_repeated_accGyroData_codec);
    if (HasMagData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(MagData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataSwim other) {
    if (other == null) {
      return;
    }
    if (other.HasTimeStamp) {
      if (!HasTimeStamp) {
        TimeStamp = new global::DateTime();
      }
      TimeStamp.MergeFrom(other.TimeStamp);
    }
    accGyroData_.Add(other.accGyroData_);
    if (other.HasMagData) {
      if (!HasMagData) {
        MagData = new global::SensorVec();
      }
      MagData.MergeFrom(other.MagData);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTimeStamp) {
            TimeStamp = new global::DateTime();
          }
          input.ReadMessage(TimeStamp);
          break;
        }
        case 18: {
          accGyroData_.AddEntriesFrom(input, _repeated_accGyroData_codec);
          break;
        }
        case 26: {
          if (!HasMagData) {
            MagData = new global::SensorVec();
          }
          input.ReadMessage(MagData);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
