// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: om0_command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from om0_command.proto</summary>
public static partial class Om0CommandReflection {

  #region Descriptor
  /// <summary>File descriptor for om0_command.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static Om0CommandReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFvbTBfY29tbWFuZC5wcm90bxoTcmVhbHRpbWVfZGF0YS5wcm90byL3AQoM",
          "T00wVHJhY2tDb25mEgwKBGhhc2gYASACKAcSEAoIYXV0b19ydW4YAiACKAgS",
          "FAoIaW50ZXJ2YWwYAyACKAc6AjMwEg0KBW1vZGVsGAQgASgJEg8KB3ZlcnNp",
          "b24YBSABKAkSFQoNZm9yY2VfdXBncmFkZRgGIAEoCBInCg9tYzMwX3Bvd2Vy",
          "X21vZGUYByABKA4yDi5NYzMwUG93ZXJtb2RlEhYKDmdwc19hdXRvX2NoZWNr",
          "GAggASgIEhkKEWdwc19pbnRlcnZhbF90aW1lGAkgASgHEh4KFkdQU19sb2Nh",
          "dGVzX2V2ZXJ5X3RpbWUYCiABKAgi7QIKDE9NMFNsZWVwRGF0YRIbCgpzbGVl",
          "cF9kYXRlGAEgAigLMgcuUnRUaW1lEhsKCnN0YXJ0X3RpbWUYAiACKAsyBy5S",
          "dFRpbWUSGQoIZW5kX3RpbWUYAyACKAsyBy5SdFRpbWUSEgoKZGVlcF9zbGVl",
          "cBgEIAIoBxITCgtsaWdodF9zbGVlcBgFIAIoBxISCgp3ZWFrX3NsZWVwGAYg",
          "AigHEhUKDWV5ZW1vdmVfc2xlZXAYByACKAcSDQoFc2NvcmUYCCACKAcSEgoK",
          "b3NhaHNfcmlzaxgJIAIoBxISCgpzcG8yX3Njb3JlGAogAigHEhwKFGF2Z19y",
          "ZXNwaXJhdGlvbl9yYXRlGAsgAigHEhwKFG1heF9yZXNwaXJhdGlvbl9yYXRl",
          "GAwgAigHEhwKFG1pbl9yZXNwaXJhdGlvbl9yYXRlGA0gAigHEhAKCHNsZWVw",
          "X2hyGA4gAigHEhEKCWNvbXBsZXRlZBgPIAIoByJSCgpPTTBDb21tYW5kEiEK",
          "CnRyYWNrX2NvbmYYASABKAsyDS5PTTBUcmFja0NvbmYSIQoKc2xlZXBfZGF0",
          "YRgCIAEoCzINLk9NMFNsZWVwRGF0YSJmCgxPTTBUcmFja0RhdGESFwoEdGlt",
          "ZRgBIAIoCzIJLkRhdGVUaW1lEhUKBGduc3MYAiABKAsyBy5SdEdOU1MSCgoC",
          "aHIYAyABKAcSGgoIZ3BzX3R5cGUYBCABKA4yCC5HUFNUWVBFIhoKC09NMFJl",
          "c3BvbnNlEgsKA3JldBgBIAIoCCLuAQoJT00wUmVwb3J0EhIKCnNvc19zaWdu",
          "YWwYASABKAgSDwoHd2FrZV91cBgCIAEoCBIhCgp0cmFja19kYXRhGAMgAygL",
          "Mg0uT00wVHJhY2tEYXRhEhsKB2JhdHRlcnkYBCABKAsyCi5SdEJhdHRlcnkS",
          "GQoGaGVhbHRoGAUgASgLMgkuUnRIZWFsdGgSHAoJZGF0ZV90aW1lGAYgASgL",
          "MgkuRGF0ZVRpbWUSDAoEcnNzaRgHIAEoBxIhCgpzbGVlcF9kYXRhGAggASgL",
          "Mg0uT00wU2xlZXBEYXRhEhIKCnNwb3J0X3R5cGUYCSABKAcqKwoNTWMzMFBv",
          "d2VybW9kZRIICgRISUdIEAASBwoDTUlEEAESBwoDTE9XEAIqPgoHR1BTVFlQ",
          "RRIICgROVUxMEAASDAoIVFlQRV9CVFMQARINCglUWVBFX1dJRkkQAhIMCghU",
          "WVBFX0dQUxADQglaBy4vaXdvd24="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Mc30Powermode), typeof(global::GPSTYPE), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::OM0TrackConf), global::OM0TrackConf.Parser, new[]{ "Hash", "AutoRun", "Interval", "Model", "Version", "ForceUpgrade", "Mc30PowerMode", "GpsAutoCheck", "GpsIntervalTime", "GPSLocatesEveryTime" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::OM0SleepData), global::OM0SleepData.Parser, new[]{ "SleepDate", "StartTime", "EndTime", "DeepSleep", "LightSleep", "WeakSleep", "EyemoveSleep", "Score", "OsahsRisk", "Spo2Score", "AvgRespirationRate", "MaxRespirationRate", "MinRespirationRate", "SleepHr", "Completed" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::OM0Command), global::OM0Command.Parser, new[]{ "TrackConf", "SleepData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::OM0TrackData), global::OM0TrackData.Parser, new[]{ "Time", "Gnss", "Hr", "GpsType" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::OM0Response), global::OM0Response.Parser, new[]{ "Ret" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::OM0Report), global::OM0Report.Parser, new[]{ "SosSignal", "WakeUp", "TrackData", "Battery", "Health", "DateTime", "Rssi", "SleepData", "SportType" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum Mc30Powermode {
  [pbr::OriginalName("HIGH")] High = 0,
  [pbr::OriginalName("MID")] Mid = 1,
  [pbr::OriginalName("LOW")] Low = 2,
}

public enum GPSTYPE {
  [pbr::OriginalName("NULL")] Null = 0,
  [pbr::OriginalName("TYPE_BTS")] TypeBts = 1,
  [pbr::OriginalName("TYPE_WIFI")] TypeWifi = 2,
  [pbr::OriginalName("TYPE_GPS")] TypeGps = 3,
}

#endregion

#region Messages
public sealed partial class OM0TrackConf : pb::IMessage<OM0TrackConf> {
  private static readonly pb::MessageParser<OM0TrackConf> _parser = new pb::MessageParser<OM0TrackConf>(() => new OM0TrackConf());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<OM0TrackConf> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Om0CommandReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0TrackConf() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0TrackConf(OM0TrackConf other) : this() {
    _hasBits0 = other._hasBits0;
    hash_ = other.hash_;
    autoRun_ = other.autoRun_;
    interval_ = other.interval_;
    model_ = other.model_;
    version_ = other.version_;
    forceUpgrade_ = other.forceUpgrade_;
    mc30PowerMode_ = other.mc30PowerMode_;
    gpsAutoCheck_ = other.gpsAutoCheck_;
    gpsIntervalTime_ = other.gpsIntervalTime_;
    gPSLocatesEveryTime_ = other.gPSLocatesEveryTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0TrackConf Clone() {
    return new OM0TrackConf(this);
  }

  /// <summary>Field number for the "hash" field.</summary>
  public const int HashFieldNumber = 1;
  private readonly static uint HashDefaultValue = 0;

  private uint hash_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Hash {
    get { if ((_hasBits0 & 1) != 0) { return hash_; } else { return HashDefaultValue; } }
    set {
      _hasBits0 |= 1;
      hash_ = value;
    }
  }
  /// <summary>Gets whether the "hash" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasHash {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "hash" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearHash() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "auto_run" field.</summary>
  public const int AutoRunFieldNumber = 2;
  private readonly static bool AutoRunDefaultValue = false;

  private bool autoRun_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool AutoRun {
    get { if ((_hasBits0 & 2) != 0) { return autoRun_; } else { return AutoRunDefaultValue; } }
    set {
      _hasBits0 |= 2;
      autoRun_ = value;
    }
  }
  /// <summary>Gets whether the "auto_run" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAutoRun {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "auto_run" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAutoRun() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "interval" field.</summary>
  public const int IntervalFieldNumber = 3;
  private readonly static uint IntervalDefaultValue = 30;

  private uint interval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Interval {
    get { if ((_hasBits0 & 4) != 0) { return interval_; } else { return IntervalDefaultValue; } }
    set {
      _hasBits0 |= 4;
      interval_ = value;
    }
  }
  /// <summary>Gets whether the "interval" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasInterval {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "interval" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearInterval() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "model" field.</summary>
  public const int ModelFieldNumber = 4;
  private readonly static string ModelDefaultValue = "";

  private string model_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Model {
    get { return model_ ?? ModelDefaultValue; }
    set {
      model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "model" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasModel {
    get { return model_ != null; }
  }
  /// <summary>Clears the value of the "model" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearModel() {
    model_ = null;
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 5;
  private readonly static string VersionDefaultValue = "";

  private string version_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Version {
    get { return version_ ?? VersionDefaultValue; }
    set {
      version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "version" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasVersion {
    get { return version_ != null; }
  }
  /// <summary>Clears the value of the "version" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearVersion() {
    version_ = null;
  }

  /// <summary>Field number for the "force_upgrade" field.</summary>
  public const int ForceUpgradeFieldNumber = 6;
  private readonly static bool ForceUpgradeDefaultValue = false;

  private bool forceUpgrade_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool ForceUpgrade {
    get { if ((_hasBits0 & 8) != 0) { return forceUpgrade_; } else { return ForceUpgradeDefaultValue; } }
    set {
      _hasBits0 |= 8;
      forceUpgrade_ = value;
    }
  }
  /// <summary>Gets whether the "force_upgrade" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasForceUpgrade {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "force_upgrade" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearForceUpgrade() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "mc30_power_mode" field.</summary>
  public const int Mc30PowerModeFieldNumber = 7;
  private readonly static global::Mc30Powermode Mc30PowerModeDefaultValue = global::Mc30Powermode.High;

  private global::Mc30Powermode mc30PowerMode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Mc30Powermode Mc30PowerMode {
    get { if ((_hasBits0 & 16) != 0) { return mc30PowerMode_; } else { return Mc30PowerModeDefaultValue; } }
    set {
      _hasBits0 |= 16;
      mc30PowerMode_ = value;
    }
  }
  /// <summary>Gets whether the "mc30_power_mode" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMc30PowerMode {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "mc30_power_mode" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMc30PowerMode() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "gps_auto_check" field.</summary>
  public const int GpsAutoCheckFieldNumber = 8;
  private readonly static bool GpsAutoCheckDefaultValue = false;

  private bool gpsAutoCheck_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool GpsAutoCheck {
    get { if ((_hasBits0 & 32) != 0) { return gpsAutoCheck_; } else { return GpsAutoCheckDefaultValue; } }
    set {
      _hasBits0 |= 32;
      gpsAutoCheck_ = value;
    }
  }
  /// <summary>Gets whether the "gps_auto_check" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGpsAutoCheck {
    get { return (_hasBits0 & 32) != 0; }
  }
  /// <summary>Clears the value of the "gps_auto_check" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGpsAutoCheck() {
    _hasBits0 &= ~32;
  }

  /// <summary>Field number for the "gps_interval_time" field.</summary>
  public const int GpsIntervalTimeFieldNumber = 9;
  private readonly static uint GpsIntervalTimeDefaultValue = 0;

  private uint gpsIntervalTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint GpsIntervalTime {
    get { if ((_hasBits0 & 64) != 0) { return gpsIntervalTime_; } else { return GpsIntervalTimeDefaultValue; } }
    set {
      _hasBits0 |= 64;
      gpsIntervalTime_ = value;
    }
  }
  /// <summary>Gets whether the "gps_interval_time" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGpsIntervalTime {
    get { return (_hasBits0 & 64) != 0; }
  }
  /// <summary>Clears the value of the "gps_interval_time" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGpsIntervalTime() {
    _hasBits0 &= ~64;
  }

  /// <summary>Field number for the "GPS_locates_every_time" field.</summary>
  public const int GPSLocatesEveryTimeFieldNumber = 10;
  private readonly static bool GPSLocatesEveryTimeDefaultValue = false;

  private bool gPSLocatesEveryTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool GPSLocatesEveryTime {
    get { if ((_hasBits0 & 128) != 0) { return gPSLocatesEveryTime_; } else { return GPSLocatesEveryTimeDefaultValue; } }
    set {
      _hasBits0 |= 128;
      gPSLocatesEveryTime_ = value;
    }
  }
  /// <summary>Gets whether the "GPS_locates_every_time" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGPSLocatesEveryTime {
    get { return (_hasBits0 & 128) != 0; }
  }
  /// <summary>Clears the value of the "GPS_locates_every_time" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGPSLocatesEveryTime() {
    _hasBits0 &= ~128;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as OM0TrackConf);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(OM0TrackConf other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Hash != other.Hash) return false;
    if (AutoRun != other.AutoRun) return false;
    if (Interval != other.Interval) return false;
    if (Model != other.Model) return false;
    if (Version != other.Version) return false;
    if (ForceUpgrade != other.ForceUpgrade) return false;
    if (Mc30PowerMode != other.Mc30PowerMode) return false;
    if (GpsAutoCheck != other.GpsAutoCheck) return false;
    if (GpsIntervalTime != other.GpsIntervalTime) return false;
    if (GPSLocatesEveryTime != other.GPSLocatesEveryTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasHash) hash ^= Hash.GetHashCode();
    if (HasAutoRun) hash ^= AutoRun.GetHashCode();
    if (HasInterval) hash ^= Interval.GetHashCode();
    if (HasModel) hash ^= Model.GetHashCode();
    if (HasVersion) hash ^= Version.GetHashCode();
    if (HasForceUpgrade) hash ^= ForceUpgrade.GetHashCode();
    if (HasMc30PowerMode) hash ^= Mc30PowerMode.GetHashCode();
    if (HasGpsAutoCheck) hash ^= GpsAutoCheck.GetHashCode();
    if (HasGpsIntervalTime) hash ^= GpsIntervalTime.GetHashCode();
    if (HasGPSLocatesEveryTime) hash ^= GPSLocatesEveryTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasHash) {
      output.WriteRawTag(13);
      output.WriteFixed32(Hash);
    }
    if (HasAutoRun) {
      output.WriteRawTag(16);
      output.WriteBool(AutoRun);
    }
    if (HasInterval) {
      output.WriteRawTag(29);
      output.WriteFixed32(Interval);
    }
    if (HasModel) {
      output.WriteRawTag(34);
      output.WriteString(Model);
    }
    if (HasVersion) {
      output.WriteRawTag(42);
      output.WriteString(Version);
    }
    if (HasForceUpgrade) {
      output.WriteRawTag(48);
      output.WriteBool(ForceUpgrade);
    }
    if (HasMc30PowerMode) {
      output.WriteRawTag(56);
      output.WriteEnum((int) Mc30PowerMode);
    }
    if (HasGpsAutoCheck) {
      output.WriteRawTag(64);
      output.WriteBool(GpsAutoCheck);
    }
    if (HasGpsIntervalTime) {
      output.WriteRawTag(77);
      output.WriteFixed32(GpsIntervalTime);
    }
    if (HasGPSLocatesEveryTime) {
      output.WriteRawTag(80);
      output.WriteBool(GPSLocatesEveryTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasHash) {
      size += 1 + 4;
    }
    if (HasAutoRun) {
      size += 1 + 1;
    }
    if (HasInterval) {
      size += 1 + 4;
    }
    if (HasModel) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
    }
    if (HasVersion) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
    }
    if (HasForceUpgrade) {
      size += 1 + 1;
    }
    if (HasMc30PowerMode) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Mc30PowerMode);
    }
    if (HasGpsAutoCheck) {
      size += 1 + 1;
    }
    if (HasGpsIntervalTime) {
      size += 1 + 4;
    }
    if (HasGPSLocatesEveryTime) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(OM0TrackConf other) {
    if (other == null) {
      return;
    }
    if (other.HasHash) {
      Hash = other.Hash;
    }
    if (other.HasAutoRun) {
      AutoRun = other.AutoRun;
    }
    if (other.HasInterval) {
      Interval = other.Interval;
    }
    if (other.HasModel) {
      Model = other.Model;
    }
    if (other.HasVersion) {
      Version = other.Version;
    }
    if (other.HasForceUpgrade) {
      ForceUpgrade = other.ForceUpgrade;
    }
    if (other.HasMc30PowerMode) {
      Mc30PowerMode = other.Mc30PowerMode;
    }
    if (other.HasGpsAutoCheck) {
      GpsAutoCheck = other.GpsAutoCheck;
    }
    if (other.HasGpsIntervalTime) {
      GpsIntervalTime = other.GpsIntervalTime;
    }
    if (other.HasGPSLocatesEveryTime) {
      GPSLocatesEveryTime = other.GPSLocatesEveryTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          Hash = input.ReadFixed32();
          break;
        }
        case 16: {
          AutoRun = input.ReadBool();
          break;
        }
        case 29: {
          Interval = input.ReadFixed32();
          break;
        }
        case 34: {
          Model = input.ReadString();
          break;
        }
        case 42: {
          Version = input.ReadString();
          break;
        }
        case 48: {
          ForceUpgrade = input.ReadBool();
          break;
        }
        case 56: {
          Mc30PowerMode = (global::Mc30Powermode) input.ReadEnum();
          break;
        }
        case 64: {
          GpsAutoCheck = input.ReadBool();
          break;
        }
        case 77: {
          GpsIntervalTime = input.ReadFixed32();
          break;
        }
        case 80: {
          GPSLocatesEveryTime = input.ReadBool();
          break;
        }
      }
    }
  }

}

public sealed partial class OM0SleepData : pb::IMessage<OM0SleepData> {
  private static readonly pb::MessageParser<OM0SleepData> _parser = new pb::MessageParser<OM0SleepData>(() => new OM0SleepData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<OM0SleepData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Om0CommandReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0SleepData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0SleepData(OM0SleepData other) : this() {
    _hasBits0 = other._hasBits0;
    sleepDate_ = other.HasSleepDate ? other.sleepDate_.Clone() : null;
    startTime_ = other.HasStartTime ? other.startTime_.Clone() : null;
    endTime_ = other.HasEndTime ? other.endTime_.Clone() : null;
    deepSleep_ = other.deepSleep_;
    lightSleep_ = other.lightSleep_;
    weakSleep_ = other.weakSleep_;
    eyemoveSleep_ = other.eyemoveSleep_;
    score_ = other.score_;
    osahsRisk_ = other.osahsRisk_;
    spo2Score_ = other.spo2Score_;
    avgRespirationRate_ = other.avgRespirationRate_;
    maxRespirationRate_ = other.maxRespirationRate_;
    minRespirationRate_ = other.minRespirationRate_;
    sleepHr_ = other.sleepHr_;
    completed_ = other.completed_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0SleepData Clone() {
    return new OM0SleepData(this);
  }

  /// <summary>Field number for the "sleep_date" field.</summary>
  public const int SleepDateFieldNumber = 1;
  private global::RtTime sleepDate_;
  /// <summary>
  /// date of sleep data		
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RtTime SleepDate {
    get { return sleepDate_; }
    set {
      sleepDate_ = value;
    }
  }
  /// <summary>Gets whether the sleep_date field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSleepDate {
    get { return sleepDate_ != null; }
  }
  /// <summary>Clears the value of the sleep_date field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSleepDate() {
    sleepDate_ = null;
  }

  /// <summary>Field number for the "start_time" field.</summary>
  public const int StartTimeFieldNumber = 2;
  private global::RtTime startTime_;
  /// <summary>
  /// sleep start time		
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RtTime StartTime {
    get { return startTime_; }
    set {
      startTime_ = value;
    }
  }
  /// <summary>Gets whether the start_time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasStartTime {
    get { return startTime_ != null; }
  }
  /// <summary>Clears the value of the start_time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearStartTime() {
    startTime_ = null;
  }

  /// <summary>Field number for the "end_time" field.</summary>
  public const int EndTimeFieldNumber = 3;
  private global::RtTime endTime_;
  /// <summary>
  /// sleep end time	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RtTime EndTime {
    get { return endTime_; }
    set {
      endTime_ = value;
    }
  }
  /// <summary>Gets whether the end_time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEndTime {
    get { return endTime_ != null; }
  }
  /// <summary>Clears the value of the end_time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEndTime() {
    endTime_ = null;
  }

  /// <summary>Field number for the "deep_sleep" field.</summary>
  public const int DeepSleepFieldNumber = 4;
  private readonly static uint DeepSleepDefaultValue = 0;

  private uint deepSleep_;
  /// <summary>
  /// minutes
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint DeepSleep {
    get { if ((_hasBits0 & 1) != 0) { return deepSleep_; } else { return DeepSleepDefaultValue; } }
    set {
      _hasBits0 |= 1;
      deepSleep_ = value;
    }
  }
  /// <summary>Gets whether the "deep_sleep" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDeepSleep {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "deep_sleep" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDeepSleep() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "light_sleep" field.</summary>
  public const int LightSleepFieldNumber = 5;
  private readonly static uint LightSleepDefaultValue = 0;

  private uint lightSleep_;
  /// <summary>
  /// minutes
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint LightSleep {
    get { if ((_hasBits0 & 2) != 0) { return lightSleep_; } else { return LightSleepDefaultValue; } }
    set {
      _hasBits0 |= 2;
      lightSleep_ = value;
    }
  }
  /// <summary>Gets whether the "light_sleep" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLightSleep {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "light_sleep" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLightSleep() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "weak_sleep" field.</summary>
  public const int WeakSleepFieldNumber = 6;
  private readonly static uint WeakSleepDefaultValue = 0;

  private uint weakSleep_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint WeakSleep {
    get { if ((_hasBits0 & 4) != 0) { return weakSleep_; } else { return WeakSleepDefaultValue; } }
    set {
      _hasBits0 |= 4;
      weakSleep_ = value;
    }
  }
  /// <summary>Gets whether the "weak_sleep" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasWeakSleep {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "weak_sleep" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearWeakSleep() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "eyemove_sleep" field.</summary>
  public const int EyemoveSleepFieldNumber = 7;
  private readonly static uint EyemoveSleepDefaultValue = 0;

  private uint eyemoveSleep_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint EyemoveSleep {
    get { if ((_hasBits0 & 8) != 0) { return eyemoveSleep_; } else { return EyemoveSleepDefaultValue; } }
    set {
      _hasBits0 |= 8;
      eyemoveSleep_ = value;
    }
  }
  /// <summary>Gets whether the "eyemove_sleep" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEyemoveSleep {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "eyemove_sleep" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEyemoveSleep() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "score" field.</summary>
  public const int ScoreFieldNumber = 8;
  private readonly static uint ScoreDefaultValue = 0;

  private uint score_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Score {
    get { if ((_hasBits0 & 16) != 0) { return score_; } else { return ScoreDefaultValue; } }
    set {
      _hasBits0 |= 16;
      score_ = value;
    }
  }
  /// <summary>Gets whether the "score" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasScore {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "score" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearScore() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "osahs_risk" field.</summary>
  public const int OsahsRiskFieldNumber = 9;
  private readonly static uint OsahsRiskDefaultValue = 0;

  private uint osahsRisk_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint OsahsRisk {
    get { if ((_hasBits0 & 32) != 0) { return osahsRisk_; } else { return OsahsRiskDefaultValue; } }
    set {
      _hasBits0 |= 32;
      osahsRisk_ = value;
    }
  }
  /// <summary>Gets whether the "osahs_risk" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasOsahsRisk {
    get { return (_hasBits0 & 32) != 0; }
  }
  /// <summary>Clears the value of the "osahs_risk" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearOsahsRisk() {
    _hasBits0 &= ~32;
  }

  /// <summary>Field number for the "spo2_score" field.</summary>
  public const int Spo2ScoreFieldNumber = 10;
  private readonly static uint Spo2ScoreDefaultValue = 0;

  private uint spo2Score_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Spo2Score {
    get { if ((_hasBits0 & 64) != 0) { return spo2Score_; } else { return Spo2ScoreDefaultValue; } }
    set {
      _hasBits0 |= 64;
      spo2Score_ = value;
    }
  }
  /// <summary>Gets whether the "spo2_score" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSpo2Score {
    get { return (_hasBits0 & 64) != 0; }
  }
  /// <summary>Clears the value of the "spo2_score" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSpo2Score() {
    _hasBits0 &= ~64;
  }

  /// <summary>Field number for the "avg_respiration_rate" field.</summary>
  public const int AvgRespirationRateFieldNumber = 11;
  private readonly static uint AvgRespirationRateDefaultValue = 0;

  private uint avgRespirationRate_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint AvgRespirationRate {
    get { if ((_hasBits0 & 128) != 0) { return avgRespirationRate_; } else { return AvgRespirationRateDefaultValue; } }
    set {
      _hasBits0 |= 128;
      avgRespirationRate_ = value;
    }
  }
  /// <summary>Gets whether the "avg_respiration_rate" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAvgRespirationRate {
    get { return (_hasBits0 & 128) != 0; }
  }
  /// <summary>Clears the value of the "avg_respiration_rate" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAvgRespirationRate() {
    _hasBits0 &= ~128;
  }

  /// <summary>Field number for the "max_respiration_rate" field.</summary>
  public const int MaxRespirationRateFieldNumber = 12;
  private readonly static uint MaxRespirationRateDefaultValue = 0;

  private uint maxRespirationRate_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint MaxRespirationRate {
    get { if ((_hasBits0 & 256) != 0) { return maxRespirationRate_; } else { return MaxRespirationRateDefaultValue; } }
    set {
      _hasBits0 |= 256;
      maxRespirationRate_ = value;
    }
  }
  /// <summary>Gets whether the "max_respiration_rate" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMaxRespirationRate {
    get { return (_hasBits0 & 256) != 0; }
  }
  /// <summary>Clears the value of the "max_respiration_rate" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMaxRespirationRate() {
    _hasBits0 &= ~256;
  }

  /// <summary>Field number for the "min_respiration_rate" field.</summary>
  public const int MinRespirationRateFieldNumber = 13;
  private readonly static uint MinRespirationRateDefaultValue = 0;

  private uint minRespirationRate_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint MinRespirationRate {
    get { if ((_hasBits0 & 512) != 0) { return minRespirationRate_; } else { return MinRespirationRateDefaultValue; } }
    set {
      _hasBits0 |= 512;
      minRespirationRate_ = value;
    }
  }
  /// <summary>Gets whether the "min_respiration_rate" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMinRespirationRate {
    get { return (_hasBits0 & 512) != 0; }
  }
  /// <summary>Clears the value of the "min_respiration_rate" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMinRespirationRate() {
    _hasBits0 &= ~512;
  }

  /// <summary>Field number for the "sleep_hr" field.</summary>
  public const int SleepHrFieldNumber = 14;
  private readonly static uint SleepHrDefaultValue = 0;

  private uint sleepHr_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint SleepHr {
    get { if ((_hasBits0 & 1024) != 0) { return sleepHr_; } else { return SleepHrDefaultValue; } }
    set {
      _hasBits0 |= 1024;
      sleepHr_ = value;
    }
  }
  /// <summary>Gets whether the "sleep_hr" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSleepHr {
    get { return (_hasBits0 & 1024) != 0; }
  }
  /// <summary>Clears the value of the "sleep_hr" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSleepHr() {
    _hasBits0 &= ~1024;
  }

  /// <summary>Field number for the "completed" field.</summary>
  public const int CompletedFieldNumber = 15;
  private readonly static uint CompletedDefaultValue = 0;

  private uint completed_;
  /// <summary>
  /// minutes	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Completed {
    get { if ((_hasBits0 & 2048) != 0) { return completed_; } else { return CompletedDefaultValue; } }
    set {
      _hasBits0 |= 2048;
      completed_ = value;
    }
  }
  /// <summary>Gets whether the "completed" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasCompleted {
    get { return (_hasBits0 & 2048) != 0; }
  }
  /// <summary>Clears the value of the "completed" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearCompleted() {
    _hasBits0 &= ~2048;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as OM0SleepData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(OM0SleepData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(SleepDate, other.SleepDate)) return false;
    if (!object.Equals(StartTime, other.StartTime)) return false;
    if (!object.Equals(EndTime, other.EndTime)) return false;
    if (DeepSleep != other.DeepSleep) return false;
    if (LightSleep != other.LightSleep) return false;
    if (WeakSleep != other.WeakSleep) return false;
    if (EyemoveSleep != other.EyemoveSleep) return false;
    if (Score != other.Score) return false;
    if (OsahsRisk != other.OsahsRisk) return false;
    if (Spo2Score != other.Spo2Score) return false;
    if (AvgRespirationRate != other.AvgRespirationRate) return false;
    if (MaxRespirationRate != other.MaxRespirationRate) return false;
    if (MinRespirationRate != other.MinRespirationRate) return false;
    if (SleepHr != other.SleepHr) return false;
    if (Completed != other.Completed) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasSleepDate) hash ^= SleepDate.GetHashCode();
    if (HasStartTime) hash ^= StartTime.GetHashCode();
    if (HasEndTime) hash ^= EndTime.GetHashCode();
    if (HasDeepSleep) hash ^= DeepSleep.GetHashCode();
    if (HasLightSleep) hash ^= LightSleep.GetHashCode();
    if (HasWeakSleep) hash ^= WeakSleep.GetHashCode();
    if (HasEyemoveSleep) hash ^= EyemoveSleep.GetHashCode();
    if (HasScore) hash ^= Score.GetHashCode();
    if (HasOsahsRisk) hash ^= OsahsRisk.GetHashCode();
    if (HasSpo2Score) hash ^= Spo2Score.GetHashCode();
    if (HasAvgRespirationRate) hash ^= AvgRespirationRate.GetHashCode();
    if (HasMaxRespirationRate) hash ^= MaxRespirationRate.GetHashCode();
    if (HasMinRespirationRate) hash ^= MinRespirationRate.GetHashCode();
    if (HasSleepHr) hash ^= SleepHr.GetHashCode();
    if (HasCompleted) hash ^= Completed.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasSleepDate) {
      output.WriteRawTag(10);
      output.WriteMessage(SleepDate);
    }
    if (HasStartTime) {
      output.WriteRawTag(18);
      output.WriteMessage(StartTime);
    }
    if (HasEndTime) {
      output.WriteRawTag(26);
      output.WriteMessage(EndTime);
    }
    if (HasDeepSleep) {
      output.WriteRawTag(37);
      output.WriteFixed32(DeepSleep);
    }
    if (HasLightSleep) {
      output.WriteRawTag(45);
      output.WriteFixed32(LightSleep);
    }
    if (HasWeakSleep) {
      output.WriteRawTag(53);
      output.WriteFixed32(WeakSleep);
    }
    if (HasEyemoveSleep) {
      output.WriteRawTag(61);
      output.WriteFixed32(EyemoveSleep);
    }
    if (HasScore) {
      output.WriteRawTag(69);
      output.WriteFixed32(Score);
    }
    if (HasOsahsRisk) {
      output.WriteRawTag(77);
      output.WriteFixed32(OsahsRisk);
    }
    if (HasSpo2Score) {
      output.WriteRawTag(85);
      output.WriteFixed32(Spo2Score);
    }
    if (HasAvgRespirationRate) {
      output.WriteRawTag(93);
      output.WriteFixed32(AvgRespirationRate);
    }
    if (HasMaxRespirationRate) {
      output.WriteRawTag(101);
      output.WriteFixed32(MaxRespirationRate);
    }
    if (HasMinRespirationRate) {
      output.WriteRawTag(109);
      output.WriteFixed32(MinRespirationRate);
    }
    if (HasSleepHr) {
      output.WriteRawTag(117);
      output.WriteFixed32(SleepHr);
    }
    if (HasCompleted) {
      output.WriteRawTag(125);
      output.WriteFixed32(Completed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasSleepDate) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SleepDate);
    }
    if (HasStartTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartTime);
    }
    if (HasEndTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndTime);
    }
    if (HasDeepSleep) {
      size += 1 + 4;
    }
    if (HasLightSleep) {
      size += 1 + 4;
    }
    if (HasWeakSleep) {
      size += 1 + 4;
    }
    if (HasEyemoveSleep) {
      size += 1 + 4;
    }
    if (HasScore) {
      size += 1 + 4;
    }
    if (HasOsahsRisk) {
      size += 1 + 4;
    }
    if (HasSpo2Score) {
      size += 1 + 4;
    }
    if (HasAvgRespirationRate) {
      size += 1 + 4;
    }
    if (HasMaxRespirationRate) {
      size += 1 + 4;
    }
    if (HasMinRespirationRate) {
      size += 1 + 4;
    }
    if (HasSleepHr) {
      size += 1 + 4;
    }
    if (HasCompleted) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(OM0SleepData other) {
    if (other == null) {
      return;
    }
    if (other.HasSleepDate) {
      if (!HasSleepDate) {
        SleepDate = new global::RtTime();
      }
      SleepDate.MergeFrom(other.SleepDate);
    }
    if (other.HasStartTime) {
      if (!HasStartTime) {
        StartTime = new global::RtTime();
      }
      StartTime.MergeFrom(other.StartTime);
    }
    if (other.HasEndTime) {
      if (!HasEndTime) {
        EndTime = new global::RtTime();
      }
      EndTime.MergeFrom(other.EndTime);
    }
    if (other.HasDeepSleep) {
      DeepSleep = other.DeepSleep;
    }
    if (other.HasLightSleep) {
      LightSleep = other.LightSleep;
    }
    if (other.HasWeakSleep) {
      WeakSleep = other.WeakSleep;
    }
    if (other.HasEyemoveSleep) {
      EyemoveSleep = other.EyemoveSleep;
    }
    if (other.HasScore) {
      Score = other.Score;
    }
    if (other.HasOsahsRisk) {
      OsahsRisk = other.OsahsRisk;
    }
    if (other.HasSpo2Score) {
      Spo2Score = other.Spo2Score;
    }
    if (other.HasAvgRespirationRate) {
      AvgRespirationRate = other.AvgRespirationRate;
    }
    if (other.HasMaxRespirationRate) {
      MaxRespirationRate = other.MaxRespirationRate;
    }
    if (other.HasMinRespirationRate) {
      MinRespirationRate = other.MinRespirationRate;
    }
    if (other.HasSleepHr) {
      SleepHr = other.SleepHr;
    }
    if (other.HasCompleted) {
      Completed = other.Completed;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasSleepDate) {
            SleepDate = new global::RtTime();
          }
          input.ReadMessage(SleepDate);
          break;
        }
        case 18: {
          if (!HasStartTime) {
            StartTime = new global::RtTime();
          }
          input.ReadMessage(StartTime);
          break;
        }
        case 26: {
          if (!HasEndTime) {
            EndTime = new global::RtTime();
          }
          input.ReadMessage(EndTime);
          break;
        }
        case 37: {
          DeepSleep = input.ReadFixed32();
          break;
        }
        case 45: {
          LightSleep = input.ReadFixed32();
          break;
        }
        case 53: {
          WeakSleep = input.ReadFixed32();
          break;
        }
        case 61: {
          EyemoveSleep = input.ReadFixed32();
          break;
        }
        case 69: {
          Score = input.ReadFixed32();
          break;
        }
        case 77: {
          OsahsRisk = input.ReadFixed32();
          break;
        }
        case 85: {
          Spo2Score = input.ReadFixed32();
          break;
        }
        case 93: {
          AvgRespirationRate = input.ReadFixed32();
          break;
        }
        case 101: {
          MaxRespirationRate = input.ReadFixed32();
          break;
        }
        case 109: {
          MinRespirationRate = input.ReadFixed32();
          break;
        }
        case 117: {
          SleepHr = input.ReadFixed32();
          break;
        }
        case 125: {
          Completed = input.ReadFixed32();
          break;
        }
      }
    }
  }

}

public sealed partial class OM0Command : pb::IMessage<OM0Command> {
  private static readonly pb::MessageParser<OM0Command> _parser = new pb::MessageParser<OM0Command>(() => new OM0Command());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<OM0Command> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Om0CommandReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Command() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Command(OM0Command other) : this() {
    trackConf_ = other.HasTrackConf ? other.trackConf_.Clone() : null;
    sleepData_ = other.HasSleepData ? other.sleepData_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Command Clone() {
    return new OM0Command(this);
  }

  /// <summary>Field number for the "track_conf" field.</summary>
  public const int TrackConfFieldNumber = 1;
  private global::OM0TrackConf trackConf_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::OM0TrackConf TrackConf {
    get { return trackConf_; }
    set {
      trackConf_ = value;
    }
  }
  /// <summary>Gets whether the track_conf field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTrackConf {
    get { return trackConf_ != null; }
  }
  /// <summary>Clears the value of the track_conf field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTrackConf() {
    trackConf_ = null;
  }

  /// <summary>Field number for the "sleep_data" field.</summary>
  public const int SleepDataFieldNumber = 2;
  private global::OM0SleepData sleepData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::OM0SleepData SleepData {
    get { return sleepData_; }
    set {
      sleepData_ = value;
    }
  }
  /// <summary>Gets whether the sleep_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSleepData {
    get { return sleepData_ != null; }
  }
  /// <summary>Clears the value of the sleep_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSleepData() {
    sleepData_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as OM0Command);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(OM0Command other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TrackConf, other.TrackConf)) return false;
    if (!object.Equals(SleepData, other.SleepData)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTrackConf) hash ^= TrackConf.GetHashCode();
    if (HasSleepData) hash ^= SleepData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTrackConf) {
      output.WriteRawTag(10);
      output.WriteMessage(TrackConf);
    }
    if (HasSleepData) {
      output.WriteRawTag(18);
      output.WriteMessage(SleepData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTrackConf) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrackConf);
    }
    if (HasSleepData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SleepData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(OM0Command other) {
    if (other == null) {
      return;
    }
    if (other.HasTrackConf) {
      if (!HasTrackConf) {
        TrackConf = new global::OM0TrackConf();
      }
      TrackConf.MergeFrom(other.TrackConf);
    }
    if (other.HasSleepData) {
      if (!HasSleepData) {
        SleepData = new global::OM0SleepData();
      }
      SleepData.MergeFrom(other.SleepData);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTrackConf) {
            TrackConf = new global::OM0TrackConf();
          }
          input.ReadMessage(TrackConf);
          break;
        }
        case 18: {
          if (!HasSleepData) {
            SleepData = new global::OM0SleepData();
          }
          input.ReadMessage(SleepData);
          break;
        }
      }
    }
  }

}

public sealed partial class OM0TrackData : pb::IMessage<OM0TrackData> {
  private static readonly pb::MessageParser<OM0TrackData> _parser = new pb::MessageParser<OM0TrackData>(() => new OM0TrackData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<OM0TrackData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Om0CommandReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0TrackData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0TrackData(OM0TrackData other) : this() {
    _hasBits0 = other._hasBits0;
    time_ = other.HasTime ? other.time_.Clone() : null;
    gnss_ = other.HasGnss ? other.gnss_.Clone() : null;
    hr_ = other.hr_;
    gpsType_ = other.gpsType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0TrackData Clone() {
    return new OM0TrackData(this);
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 1;
  private global::DateTime time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }
  /// <summary>Gets whether the time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTime() {
    time_ = null;
  }

  /// <summary>Field number for the "gnss" field.</summary>
  public const int GnssFieldNumber = 2;
  private global::RtGNSS gnss_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RtGNSS Gnss {
    get { return gnss_; }
    set {
      gnss_ = value;
    }
  }
  /// <summary>Gets whether the gnss field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGnss {
    get { return gnss_ != null; }
  }
  /// <summary>Clears the value of the gnss field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGnss() {
    gnss_ = null;
  }

  /// <summary>Field number for the "hr" field.</summary>
  public const int HrFieldNumber = 3;
  private readonly static uint HrDefaultValue = 0;

  private uint hr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Hr {
    get { if ((_hasBits0 & 1) != 0) { return hr_; } else { return HrDefaultValue; } }
    set {
      _hasBits0 |= 1;
      hr_ = value;
    }
  }
  /// <summary>Gets whether the "hr" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasHr {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "hr" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearHr() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "gps_type" field.</summary>
  public const int GpsTypeFieldNumber = 4;
  private readonly static global::GPSTYPE GpsTypeDefaultValue = global::GPSTYPE.Null;

  private global::GPSTYPE gpsType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::GPSTYPE GpsType {
    get { if ((_hasBits0 & 2) != 0) { return gpsType_; } else { return GpsTypeDefaultValue; } }
    set {
      _hasBits0 |= 2;
      gpsType_ = value;
    }
  }
  /// <summary>Gets whether the "gps_type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGpsType {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "gps_type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGpsType() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as OM0TrackData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(OM0TrackData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Time, other.Time)) return false;
    if (!object.Equals(Gnss, other.Gnss)) return false;
    if (Hr != other.Hr) return false;
    if (GpsType != other.GpsType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTime) hash ^= Time.GetHashCode();
    if (HasGnss) hash ^= Gnss.GetHashCode();
    if (HasHr) hash ^= Hr.GetHashCode();
    if (HasGpsType) hash ^= GpsType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTime) {
      output.WriteRawTag(10);
      output.WriteMessage(Time);
    }
    if (HasGnss) {
      output.WriteRawTag(18);
      output.WriteMessage(Gnss);
    }
    if (HasHr) {
      output.WriteRawTag(29);
      output.WriteFixed32(Hr);
    }
    if (HasGpsType) {
      output.WriteRawTag(32);
      output.WriteEnum((int) GpsType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
    }
    if (HasGnss) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gnss);
    }
    if (HasHr) {
      size += 1 + 4;
    }
    if (HasGpsType) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GpsType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(OM0TrackData other) {
    if (other == null) {
      return;
    }
    if (other.HasTime) {
      if (!HasTime) {
        Time = new global::DateTime();
      }
      Time.MergeFrom(other.Time);
    }
    if (other.HasGnss) {
      if (!HasGnss) {
        Gnss = new global::RtGNSS();
      }
      Gnss.MergeFrom(other.Gnss);
    }
    if (other.HasHr) {
      Hr = other.Hr;
    }
    if (other.HasGpsType) {
      GpsType = other.GpsType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTime) {
            Time = new global::DateTime();
          }
          input.ReadMessage(Time);
          break;
        }
        case 18: {
          if (!HasGnss) {
            Gnss = new global::RtGNSS();
          }
          input.ReadMessage(Gnss);
          break;
        }
        case 29: {
          Hr = input.ReadFixed32();
          break;
        }
        case 32: {
          GpsType = (global::GPSTYPE) input.ReadEnum();
          break;
        }
      }
    }
  }

}

public sealed partial class OM0Response : pb::IMessage<OM0Response> {
  private static readonly pb::MessageParser<OM0Response> _parser = new pb::MessageParser<OM0Response>(() => new OM0Response());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<OM0Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Om0CommandReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Response(OM0Response other) : this() {
    _hasBits0 = other._hasBits0;
    ret_ = other.ret_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Response Clone() {
    return new OM0Response(this);
  }

  /// <summary>Field number for the "ret" field.</summary>
  public const int RetFieldNumber = 1;
  private readonly static bool RetDefaultValue = false;

  private bool ret_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Ret {
    get { if ((_hasBits0 & 1) != 0) { return ret_; } else { return RetDefaultValue; } }
    set {
      _hasBits0 |= 1;
      ret_ = value;
    }
  }
  /// <summary>Gets whether the "ret" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRet {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "ret" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRet() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as OM0Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(OM0Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Ret != other.Ret) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasRet) hash ^= Ret.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasRet) {
      output.WriteRawTag(8);
      output.WriteBool(Ret);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasRet) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(OM0Response other) {
    if (other == null) {
      return;
    }
    if (other.HasRet) {
      Ret = other.Ret;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Ret = input.ReadBool();
          break;
        }
      }
    }
  }

}

public sealed partial class OM0Report : pb::IMessage<OM0Report> {
  private static readonly pb::MessageParser<OM0Report> _parser = new pb::MessageParser<OM0Report>(() => new OM0Report());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<OM0Report> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Om0CommandReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Report() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Report(OM0Report other) : this() {
    _hasBits0 = other._hasBits0;
    sosSignal_ = other.sosSignal_;
    wakeUp_ = other.wakeUp_;
    trackData_ = other.trackData_.Clone();
    battery_ = other.HasBattery ? other.battery_.Clone() : null;
    health_ = other.HasHealth ? other.health_.Clone() : null;
    dateTime_ = other.HasDateTime ? other.dateTime_.Clone() : null;
    rssi_ = other.rssi_;
    sleepData_ = other.HasSleepData ? other.sleepData_.Clone() : null;
    sportType_ = other.sportType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OM0Report Clone() {
    return new OM0Report(this);
  }

  /// <summary>Field number for the "sos_signal" field.</summary>
  public const int SosSignalFieldNumber = 1;
  private readonly static bool SosSignalDefaultValue = false;

  private bool sosSignal_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool SosSignal {
    get { if ((_hasBits0 & 1) != 0) { return sosSignal_; } else { return SosSignalDefaultValue; } }
    set {
      _hasBits0 |= 1;
      sosSignal_ = value;
    }
  }
  /// <summary>Gets whether the "sos_signal" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSosSignal {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "sos_signal" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSosSignal() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "wake_up" field.</summary>
  public const int WakeUpFieldNumber = 2;
  private readonly static bool WakeUpDefaultValue = false;

  private bool wakeUp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool WakeUp {
    get { if ((_hasBits0 & 2) != 0) { return wakeUp_; } else { return WakeUpDefaultValue; } }
    set {
      _hasBits0 |= 2;
      wakeUp_ = value;
    }
  }
  /// <summary>Gets whether the "wake_up" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasWakeUp {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "wake_up" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearWakeUp() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "track_data" field.</summary>
  public const int TrackDataFieldNumber = 3;
  private static readonly pb::FieldCodec<global::OM0TrackData> _repeated_trackData_codec
      = pb::FieldCodec.ForMessage(26, global::OM0TrackData.Parser);
  private readonly pbc::RepeatedField<global::OM0TrackData> trackData_ = new pbc::RepeatedField<global::OM0TrackData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::OM0TrackData> TrackData {
    get { return trackData_; }
  }

  /// <summary>Field number for the "battery" field.</summary>
  public const int BatteryFieldNumber = 4;
  private global::RtBattery battery_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RtBattery Battery {
    get { return battery_; }
    set {
      battery_ = value;
    }
  }
  /// <summary>Gets whether the battery field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBattery {
    get { return battery_ != null; }
  }
  /// <summary>Clears the value of the battery field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBattery() {
    battery_ = null;
  }

  /// <summary>Field number for the "health" field.</summary>
  public const int HealthFieldNumber = 5;
  private global::RtHealth health_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RtHealth Health {
    get { return health_; }
    set {
      health_ = value;
    }
  }
  /// <summary>Gets whether the health field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasHealth {
    get { return health_ != null; }
  }
  /// <summary>Clears the value of the health field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearHealth() {
    health_ = null;
  }

  /// <summary>Field number for the "date_time" field.</summary>
  public const int DateTimeFieldNumber = 6;
  private global::DateTime dateTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime DateTime {
    get { return dateTime_; }
    set {
      dateTime_ = value;
    }
  }
  /// <summary>Gets whether the date_time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDateTime {
    get { return dateTime_ != null; }
  }
  /// <summary>Clears the value of the date_time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDateTime() {
    dateTime_ = null;
  }

  /// <summary>Field number for the "rssi" field.</summary>
  public const int RssiFieldNumber = 7;
  private readonly static uint RssiDefaultValue = 0;

  private uint rssi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Rssi {
    get { if ((_hasBits0 & 4) != 0) { return rssi_; } else { return RssiDefaultValue; } }
    set {
      _hasBits0 |= 4;
      rssi_ = value;
    }
  }
  /// <summary>Gets whether the "rssi" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRssi {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "rssi" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRssi() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "sleep_data" field.</summary>
  public const int SleepDataFieldNumber = 8;
  private global::OM0SleepData sleepData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::OM0SleepData SleepData {
    get { return sleepData_; }
    set {
      sleepData_ = value;
    }
  }
  /// <summary>Gets whether the sleep_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSleepData {
    get { return sleepData_ != null; }
  }
  /// <summary>Clears the value of the sleep_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSleepData() {
    sleepData_ = null;
  }

  /// <summary>Field number for the "sport_type" field.</summary>
  public const int SportTypeFieldNumber = 9;
  private readonly static uint SportTypeDefaultValue = 0;

  private uint sportType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint SportType {
    get { if ((_hasBits0 & 8) != 0) { return sportType_; } else { return SportTypeDefaultValue; } }
    set {
      _hasBits0 |= 8;
      sportType_ = value;
    }
  }
  /// <summary>Gets whether the "sport_type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSportType {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "sport_type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSportType() {
    _hasBits0 &= ~8;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as OM0Report);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(OM0Report other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SosSignal != other.SosSignal) return false;
    if (WakeUp != other.WakeUp) return false;
    if(!trackData_.Equals(other.trackData_)) return false;
    if (!object.Equals(Battery, other.Battery)) return false;
    if (!object.Equals(Health, other.Health)) return false;
    if (!object.Equals(DateTime, other.DateTime)) return false;
    if (Rssi != other.Rssi) return false;
    if (!object.Equals(SleepData, other.SleepData)) return false;
    if (SportType != other.SportType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasSosSignal) hash ^= SosSignal.GetHashCode();
    if (HasWakeUp) hash ^= WakeUp.GetHashCode();
    hash ^= trackData_.GetHashCode();
    if (HasBattery) hash ^= Battery.GetHashCode();
    if (HasHealth) hash ^= Health.GetHashCode();
    if (HasDateTime) hash ^= DateTime.GetHashCode();
    if (HasRssi) hash ^= Rssi.GetHashCode();
    if (HasSleepData) hash ^= SleepData.GetHashCode();
    if (HasSportType) hash ^= SportType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasSosSignal) {
      output.WriteRawTag(8);
      output.WriteBool(SosSignal);
    }
    if (HasWakeUp) {
      output.WriteRawTag(16);
      output.WriteBool(WakeUp);
    }
    trackData_.WriteTo(output, _repeated_trackData_codec);
    if (HasBattery) {
      output.WriteRawTag(34);
      output.WriteMessage(Battery);
    }
    if (HasHealth) {
      output.WriteRawTag(42);
      output.WriteMessage(Health);
    }
    if (HasDateTime) {
      output.WriteRawTag(50);
      output.WriteMessage(DateTime);
    }
    if (HasRssi) {
      output.WriteRawTag(61);
      output.WriteFixed32(Rssi);
    }
    if (HasSleepData) {
      output.WriteRawTag(66);
      output.WriteMessage(SleepData);
    }
    if (HasSportType) {
      output.WriteRawTag(77);
      output.WriteFixed32(SportType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasSosSignal) {
      size += 1 + 1;
    }
    if (HasWakeUp) {
      size += 1 + 1;
    }
    size += trackData_.CalculateSize(_repeated_trackData_codec);
    if (HasBattery) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Battery);
    }
    if (HasHealth) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Health);
    }
    if (HasDateTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DateTime);
    }
    if (HasRssi) {
      size += 1 + 4;
    }
    if (HasSleepData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SleepData);
    }
    if (HasSportType) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(OM0Report other) {
    if (other == null) {
      return;
    }
    if (other.HasSosSignal) {
      SosSignal = other.SosSignal;
    }
    if (other.HasWakeUp) {
      WakeUp = other.WakeUp;
    }
    trackData_.Add(other.trackData_);
    if (other.HasBattery) {
      if (!HasBattery) {
        Battery = new global::RtBattery();
      }
      Battery.MergeFrom(other.Battery);
    }
    if (other.HasHealth) {
      if (!HasHealth) {
        Health = new global::RtHealth();
      }
      Health.MergeFrom(other.Health);
    }
    if (other.HasDateTime) {
      if (!HasDateTime) {
        DateTime = new global::DateTime();
      }
      DateTime.MergeFrom(other.DateTime);
    }
    if (other.HasRssi) {
      Rssi = other.Rssi;
    }
    if (other.HasSleepData) {
      if (!HasSleepData) {
        SleepData = new global::OM0SleepData();
      }
      SleepData.MergeFrom(other.SleepData);
    }
    if (other.HasSportType) {
      SportType = other.SportType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SosSignal = input.ReadBool();
          break;
        }
        case 16: {
          WakeUp = input.ReadBool();
          break;
        }
        case 26: {
          trackData_.AddEntriesFrom(input, _repeated_trackData_codec);
          break;
        }
        case 34: {
          if (!HasBattery) {
            Battery = new global::RtBattery();
          }
          input.ReadMessage(Battery);
          break;
        }
        case 42: {
          if (!HasHealth) {
            Health = new global::RtHealth();
          }
          input.ReadMessage(Health);
          break;
        }
        case 50: {
          if (!HasDateTime) {
            DateTime = new global::DateTime();
          }
          input.ReadMessage(DateTime);
          break;
        }
        case 61: {
          Rssi = input.ReadFixed32();
          break;
        }
        case 66: {
          if (!HasSleepData) {
            SleepData = new global::OM0SleepData();
          }
          input.ReadMessage(SleepData);
          break;
        }
        case 77: {
          SportType = input.ReadFixed32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
