// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThirdParty_health_data_V2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThirdParty_health_data_V2.proto</summary>
public static partial class ThirdPartyHealthDataV2Reflection {

  #region Descriptor
  /// <summary>File descriptor for ThirdParty_health_data_V2.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThirdPartyHealthDataV2Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch9UaGlyZFBhcnR5X2hlYWx0aF9kYXRhX1YyLnByb3RvGhNyZWFsdGltZV9k",
          "YXRhLnByb3RvIlUKEk1hdHRyZXNzRGF0YUhlYWx0aBIaChJQaHlzaWNhbF9T",
          "aWduc0RhdGEYASACKAwSIwoQQWNxdWlzaXRpb25fdGltZRgCIAIoCzIJLkRh",
          "dGVUaW1lIkoKE0hpc0RhdGFUaGlyZFBhcnR5VjISKwoMTWF0dHJlc3NEYXRh",
          "GAEgASgLMhMuTWF0dHJlc3NEYXRhSGVhbHRoSABCBgoEZGF0YUIJWgcuL2l3",
          "b3du"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MattressDataHealth), global::MattressDataHealth.Parser, new[]{ "PhysicalSignsData", "AcquisitionTime" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataThirdPartyV2), global::HisDataThirdPartyV2.Parser, new[]{ "MattressData" }, new[]{ "Data" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class MattressDataHealth : pb::IMessage<MattressDataHealth> {
  private static readonly pb::MessageParser<MattressDataHealth> _parser = new pb::MessageParser<MattressDataHealth>(() => new MattressDataHealth());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MattressDataHealth> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataV2Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MattressDataHealth() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MattressDataHealth(MattressDataHealth other) : this() {
    physicalSignsData_ = other.physicalSignsData_;
    acquisitionTime_ = other.HasAcquisitionTime ? other.acquisitionTime_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MattressDataHealth Clone() {
    return new MattressDataHealth(this);
  }

  /// <summary>Field number for the "Physical_SignsData" field.</summary>
  public const int PhysicalSignsDataFieldNumber = 1;
  private readonly static pb::ByteString PhysicalSignsDataDefaultValue = pb::ByteString.Empty;

  private pb::ByteString physicalSignsData_;
  /// <summary>
  /// Physical signs
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString PhysicalSignsData {
    get { return physicalSignsData_ ?? PhysicalSignsDataDefaultValue; }
    set {
      physicalSignsData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Physical_SignsData" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPhysicalSignsData {
    get { return physicalSignsData_ != null; }
  }
  /// <summary>Clears the value of the "Physical_SignsData" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPhysicalSignsData() {
    physicalSignsData_ = null;
  }

  /// <summary>Field number for the "Acquisition_time" field.</summary>
  public const int AcquisitionTimeFieldNumber = 2;
  private global::DateTime acquisitionTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime AcquisitionTime {
    get { return acquisitionTime_; }
    set {
      acquisitionTime_ = value;
    }
  }
  /// <summary>Gets whether the Acquisition_time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAcquisitionTime {
    get { return acquisitionTime_ != null; }
  }
  /// <summary>Clears the value of the Acquisition_time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAcquisitionTime() {
    acquisitionTime_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MattressDataHealth);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MattressDataHealth other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PhysicalSignsData != other.PhysicalSignsData) return false;
    if (!object.Equals(AcquisitionTime, other.AcquisitionTime)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPhysicalSignsData) hash ^= PhysicalSignsData.GetHashCode();
    if (HasAcquisitionTime) hash ^= AcquisitionTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasPhysicalSignsData) {
      output.WriteRawTag(10);
      output.WriteBytes(PhysicalSignsData);
    }
    if (HasAcquisitionTime) {
      output.WriteRawTag(18);
      output.WriteMessage(AcquisitionTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasPhysicalSignsData) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(PhysicalSignsData);
    }
    if (HasAcquisitionTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(AcquisitionTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MattressDataHealth other) {
    if (other == null) {
      return;
    }
    if (other.HasPhysicalSignsData) {
      PhysicalSignsData = other.PhysicalSignsData;
    }
    if (other.HasAcquisitionTime) {
      if (!HasAcquisitionTime) {
        AcquisitionTime = new global::DateTime();
      }
      AcquisitionTime.MergeFrom(other.AcquisitionTime);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          PhysicalSignsData = input.ReadBytes();
          break;
        }
        case 18: {
          if (!HasAcquisitionTime) {
            AcquisitionTime = new global::DateTime();
          }
          input.ReadMessage(AcquisitionTime);
          break;
        }
      }
    }
  }

}

public sealed partial class HisDataThirdPartyV2 : pb::IMessage<HisDataThirdPartyV2> {
  private static readonly pb::MessageParser<HisDataThirdPartyV2> _parser = new pb::MessageParser<HisDataThirdPartyV2>(() => new HisDataThirdPartyV2());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataThirdPartyV2> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataV2Reflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataThirdPartyV2() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataThirdPartyV2(HisDataThirdPartyV2 other) : this() {
    switch (other.DataCase) {
      case DataOneofCase.MattressData:
        MattressData = other.MattressData.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataThirdPartyV2 Clone() {
    return new HisDataThirdPartyV2(this);
  }

  /// <summary>Field number for the "MattressData" field.</summary>
  public const int MattressDataFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::MattressDataHealth MattressData {
    get { return HasMattressData ? (global::MattressDataHealth) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.MattressData;
    }
  }
  /// <summary>Gets whether the "MattressData" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMattressData {
    get { return dataCase_ == DataOneofCase.MattressData; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "MattressData" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMattressData() {
    if (HasMattressData) {
      ClearData();
    }
  }

  private object data_;
  /// <summary>Enum of possible cases for the "data" oneof.</summary>
  public enum DataOneofCase {
    None = 0,
    MattressData = 1,
  }
  private DataOneofCase dataCase_ = DataOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DataOneofCase DataCase {
    get { return dataCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearData() {
    dataCase_ = DataOneofCase.None;
    data_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataThirdPartyV2);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataThirdPartyV2 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(MattressData, other.MattressData)) return false;
    if (DataCase != other.DataCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasMattressData) hash ^= MattressData.GetHashCode();
    hash ^= (int) dataCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasMattressData) {
      output.WriteRawTag(10);
      output.WriteMessage(MattressData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasMattressData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(MattressData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataThirdPartyV2 other) {
    if (other == null) {
      return;
    }
    switch (other.DataCase) {
      case DataOneofCase.MattressData:
        if (MattressData == null) {
          MattressData = new global::MattressDataHealth();
        }
        MattressData.MergeFrom(other.MattressData);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::MattressDataHealth subBuilder = new global::MattressDataHealth();
          if (HasMattressData) {
            subBuilder.MergeFrom(MattressData);
          }
          input.ReadMessage(subBuilder);
          MattressData = subBuilder;
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
