// <auto-generated />
using System;
using SmartWatch4G.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SmartWatch4G.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.AlarmEventRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("AlarmTime").IsRequired().HasColumnType("TEXT");
                b.Property<string>("AlarmType").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("DeviceId").HasColumnType("TEXT");
                b.Property<string>("Notes").HasColumnType("TEXT");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<double?>("Value1").HasColumnType("REAL");
                b.Property<double?>("Value2").HasColumnType("REAL");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "AlarmType", "AlarmTime");
                b.ToTable("AlarmEventRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.CallLogRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("AlarmLat").HasColumnType("TEXT");
                b.Property<string>("AlarmLon").HasColumnType("TEXT");
                b.Property<string>("AlarmTime").HasColumnType("TEXT");
                b.Property<int>("CallStatus").HasColumnType("INTEGER");
                b.Property<string>("CallNumber").HasColumnType("TEXT");
                b.Property<string>("DeviceId").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("EndTime").HasColumnType("TEXT");
                b.Property<bool>("IsSosAlarm").HasColumnType("INTEGER");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<string>("StartTime").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "IsSosAlarm");
                b.ToTable("CallLogRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.DeviceInfoRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Band").IsRequired().HasColumnType("TEXT");
                b.Property<string>("BandDetail").IsRequired().HasColumnType("TEXT");
                b.Property<string>("CommunicationMode").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("DeviceId").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("Imsi").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Mac").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Model").IsRequired().HasColumnType("TEXT");
                b.Property<string>("NetOperator").IsRequired().HasColumnType("TEXT");
                b.Property<string>("NetType").IsRequired().HasColumnType("TEXT");
                b.Property<string>("NetworkStatus").IsRequired().HasColumnType("TEXT");
                b.Property<string>("RefSignal").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Sim1CellId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Sim1IccId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Sim1NetAdhere").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Sn").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.Property<string>("Version").IsRequired().HasColumnType("TEXT");
                b.Property<int>("WatchEvent").HasColumnType("INTEGER");
                b.Property<string>("WearingStatus").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("DeviceId").IsUnique();
                b.ToTable("DeviceInfoRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.DeviceStatusRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("DeviceId").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("EventTime").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "ReceivedAt");
                b.ToTable("DeviceStatusRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.EcgDataRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("DataTime").IsRequired().HasColumnType("TEXT");
                b.Property<string>("DeviceId").HasColumnType("TEXT");
                b.Property<string>("RawDataBase64").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<int>("SampleCount").HasColumnType("INTEGER");
                b.Property<long>("Seq").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "DataTime");
                b.ToTable("EcgDataRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.GnssTrackRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int?>("BatteryLevel").HasColumnType("INTEGER");
                b.Property<float?>("CaloriesKcal").HasColumnType("REAL");
                b.Property<string>("DeviceId").HasColumnType("TEXT");
                b.Property<float?>("DistanceMetres").HasColumnType("REAL");
                b.Property<string>("GpsType").HasColumnType("TEXT");
                b.Property<double>("Latitude").HasColumnType("REAL");
                b.Property<double>("Longitude").HasColumnType("REAL");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<int?>("Rssi").HasColumnType("INTEGER");
                b.Property<long?>("Steps").HasColumnType("INTEGER");
                b.Property<string>("TrackTime").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "TrackTime");
                b.ToTable("GnssTrackRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.HealthDataRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<long?>("ActivityState").HasColumnType("INTEGER");
                b.Property<long?>("ActivityType").HasColumnType("INTEGER");
                b.Property<float?>("AxillaryTemp").HasColumnType("REAL");
                b.Property<long?>("AvgHeartRate").HasColumnType("INTEGER");
                b.Property<long?>("AvgSpo2").HasColumnType("INTEGER");
                b.Property<int?>("BiozR").HasColumnType("INTEGER");
                b.Property<int?>("BiozX").HasColumnType("INTEGER");
                b.Property<float?>("BloodPotassium").HasColumnType("REAL");
                b.Property<float?>("BloodSugar").HasColumnType("REAL");
                b.Property<float?>("Bmi").HasColumnType("REAL");
                b.Property<float?>("BodyFat").HasColumnType("REAL");
                b.Property<float?>("CaloriesKcal").HasColumnType("REAL");
                b.Property<string>("DataTime").IsRequired().HasColumnType("TEXT");
                b.Property<long?>("Dbp").HasColumnType("INTEGER");
                b.Property<string>("DeviceId").HasColumnType("TEXT");
                b.Property<float?>("EnvTemp").HasColumnType("REAL");
                b.Property<float?>("EstimatedTemp").HasColumnType("REAL");
                b.Property<int?>("Fatigue").HasColumnType("INTEGER");
                b.Property<double?>("HrvMean").HasColumnType("REAL");
                b.Property<double?>("HrvPnn50").HasColumnType("REAL");
                b.Property<double?>("HrvRmssd").HasColumnType("REAL");
                b.Property<double?>("HrvSdnn").HasColumnType("REAL");
                b.Property<long?>("MaxHeartRate").HasColumnType("INTEGER");
                b.Property<long?>("MaxSpo2").HasColumnType("INTEGER");
                b.Property<long?>("MinHeartRate").HasColumnType("INTEGER");
                b.Property<long?>("MinSpo2").HasColumnType("INTEGER");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<long?>("Sbp").HasColumnType("INTEGER");
                b.Property<long>("Seq").HasColumnType("INTEGER");
                b.Property<float?>("ShellTemp").HasColumnType("REAL");
                b.Property<string>("SleepDataJson").HasColumnType("TEXT");
                b.Property<long?>("Steps").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "DataTime");
                b.ToTable("HealthDataRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.RriDataRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("DataTime").IsRequired().HasColumnType("TEXT");
                b.Property<string>("DeviceId").HasColumnType("TEXT");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<string>("RriValuesJson").IsRequired().HasColumnType("TEXT");
                b.Property<int>("SampleCount").HasColumnType("INTEGER");
                b.Property<long>("Seq").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "DataTime");
                b.ToTable("RriDataRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.SleepDataRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("DataTime").IsRequired().HasColumnType("TEXT");
                b.Property<string>("DeviceId").HasColumnType("TEXT");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<long>("Seq").HasColumnType("INTEGER");
                b.Property<string>("SleepDate").IsRequired().HasColumnType("TEXT");
                b.Property<string>("SleepJson").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "SleepDate", "Seq");
                b.ToTable("SleepDataRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.Spo2DataRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("DeviceId").HasColumnType("TEXT");
                b.Property<string>("DataTime").IsRequired().HasColumnType("TEXT");
                b.Property<int>("Spo2").HasColumnType("INTEGER");
                b.Property<int>("HeartRate").HasColumnType("INTEGER");
                b.Property<int>("Perfusion").HasColumnType("INTEGER");
                b.Property<int>("Touch").HasColumnType("INTEGER");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "DataTime");
                b.ToTable("Spo2DataRecords");
            });

            modelBuilder.Entity("SmartWatch4G.Domain.Entities.AccDataRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("DeviceId").HasColumnType("TEXT");
                b.Property<string>("DataTime").IsRequired().HasColumnType("TEXT");
                b.Property<string>("XValuesJson").IsRequired().HasColumnType("TEXT");
                b.Property<string>("YValuesJson").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ZValuesJson").IsRequired().HasColumnType("TEXT");
                b.Property<int>("SampleCount").HasColumnType("INTEGER");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("DeviceId", "DataTime");
                b.ToTable("AccDataRecords");
            });
#pragma warning restore 612, 618
        }
    }
}
