// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: his_encrypt_ecg_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from his_encrypt_ecg_data.proto</summary>
public static partial class HisEncryptEcgDataReflection {

  #region Descriptor
  /// <summary>File descriptor for his_encrypt_ecg_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HisEncryptEcgDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpoaXNfZW5jcnlwdF9lY2dfZGF0YS5wcm90bxoTcmVhbHRpbWVfZGF0YS5w",
          "cm90bxoSaGlzX2VjZ19kYXRhLnByb3RvIlAKDUhpc0VDR0VuY3J5cHQSHwoK",
          "ZWNnZW5jcnlwdBgBIAIoCzILLkhpc0RhdGFFQ0cSDgoGUmFuZG9tGAIgAigM",
          "Eg4KBkJsZU1hYxgDIAIoDCJMChFIaXNEYXRhRUNHRW5jcnlwdBIfCgdoaXNf",
          "ZWNnGAEgAigLMg4uSGlzRUNHRW5jcnlwdBIWCg5zaWduYXR1cmVfZGF0YRgC",
          "IAIoDEIJWgcuL2l3b3du"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, global::HisEcgDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HisECGEncrypt), global::HisECGEncrypt.Parser, new[]{ "Ecgencrypt", "Random", "BleMac" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataECGEncrypt), global::HisDataECGEncrypt.Parser, new[]{ "HisEcg", "SignatureData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HisECGEncrypt : pb::IMessage<HisECGEncrypt> {
  private static readonly pb::MessageParser<HisECGEncrypt> _parser = new pb::MessageParser<HisECGEncrypt>(() => new HisECGEncrypt());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisECGEncrypt> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisEncryptEcgDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisECGEncrypt() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisECGEncrypt(HisECGEncrypt other) : this() {
    ecgencrypt_ = other.HasEcgencrypt ? other.ecgencrypt_.Clone() : null;
    random_ = other.random_;
    bleMac_ = other.bleMac_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisECGEncrypt Clone() {
    return new HisECGEncrypt(this);
  }

  /// <summary>Field number for the "ecgencrypt" field.</summary>
  public const int EcgencryptFieldNumber = 1;
  private global::HisDataECG ecgencrypt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::HisDataECG Ecgencrypt {
    get { return ecgencrypt_; }
    set {
      ecgencrypt_ = value;
    }
  }
  /// <summary>Gets whether the ecgencrypt field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEcgencrypt {
    get { return ecgencrypt_ != null; }
  }
  /// <summary>Clears the value of the ecgencrypt field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEcgencrypt() {
    ecgencrypt_ = null;
  }

  /// <summary>Field number for the "Random" field.</summary>
  public const int RandomFieldNumber = 2;
  private readonly static pb::ByteString RandomDefaultValue = pb::ByteString.Empty;

  private pb::ByteString random_;
  /// <summary>
  ///random number 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Random {
    get { return random_ ?? RandomDefaultValue; }
    set {
      random_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Random" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRandom {
    get { return random_ != null; }
  }
  /// <summary>Clears the value of the "Random" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRandom() {
    random_ = null;
  }

  /// <summary>Field number for the "BleMac" field.</summary>
  public const int BleMacFieldNumber = 3;
  private readonly static pb::ByteString BleMacDefaultValue = pb::ByteString.Empty;

  private pb::ByteString bleMac_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString BleMac {
    get { return bleMac_ ?? BleMacDefaultValue; }
    set {
      bleMac_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "BleMac" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBleMac {
    get { return bleMac_ != null; }
  }
  /// <summary>Clears the value of the "BleMac" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBleMac() {
    bleMac_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisECGEncrypt);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisECGEncrypt other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Ecgencrypt, other.Ecgencrypt)) return false;
    if (Random != other.Random) return false;
    if (BleMac != other.BleMac) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasEcgencrypt) hash ^= Ecgencrypt.GetHashCode();
    if (HasRandom) hash ^= Random.GetHashCode();
    if (HasBleMac) hash ^= BleMac.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasEcgencrypt) {
      output.WriteRawTag(10);
      output.WriteMessage(Ecgencrypt);
    }
    if (HasRandom) {
      output.WriteRawTag(18);
      output.WriteBytes(Random);
    }
    if (HasBleMac) {
      output.WriteRawTag(26);
      output.WriteBytes(BleMac);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasEcgencrypt) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ecgencrypt);
    }
    if (HasRandom) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Random);
    }
    if (HasBleMac) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(BleMac);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisECGEncrypt other) {
    if (other == null) {
      return;
    }
    if (other.HasEcgencrypt) {
      if (!HasEcgencrypt) {
        Ecgencrypt = new global::HisDataECG();
      }
      Ecgencrypt.MergeFrom(other.Ecgencrypt);
    }
    if (other.HasRandom) {
      Random = other.Random;
    }
    if (other.HasBleMac) {
      BleMac = other.BleMac;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasEcgencrypt) {
            Ecgencrypt = new global::HisDataECG();
          }
          input.ReadMessage(Ecgencrypt);
          break;
        }
        case 18: {
          Random = input.ReadBytes();
          break;
        }
        case 26: {
          BleMac = input.ReadBytes();
          break;
        }
      }
    }
  }

}

public sealed partial class HisDataECGEncrypt : pb::IMessage<HisDataECGEncrypt> {
  private static readonly pb::MessageParser<HisDataECGEncrypt> _parser = new pb::MessageParser<HisDataECGEncrypt>(() => new HisDataECGEncrypt());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataECGEncrypt> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisEncryptEcgDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataECGEncrypt() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataECGEncrypt(HisDataECGEncrypt other) : this() {
    hisEcg_ = other.HasHisEcg ? other.hisEcg_.Clone() : null;
    signatureData_ = other.signatureData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataECGEncrypt Clone() {
    return new HisDataECGEncrypt(this);
  }

  /// <summary>Field number for the "his_ecg" field.</summary>
  public const int HisEcgFieldNumber = 1;
  private global::HisECGEncrypt hisEcg_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::HisECGEncrypt HisEcg {
    get { return hisEcg_; }
    set {
      hisEcg_ = value;
    }
  }
  /// <summary>Gets whether the his_ecg field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasHisEcg {
    get { return hisEcg_ != null; }
  }
  /// <summary>Clears the value of the his_ecg field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearHisEcg() {
    hisEcg_ = null;
  }

  /// <summary>Field number for the "signature_data" field.</summary>
  public const int SignatureDataFieldNumber = 2;
  private readonly static pb::ByteString SignatureDataDefaultValue = pb::ByteString.Empty;

  private pb::ByteString signatureData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString SignatureData {
    get { return signatureData_ ?? SignatureDataDefaultValue; }
    set {
      signatureData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "signature_data" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSignatureData {
    get { return signatureData_ != null; }
  }
  /// <summary>Clears the value of the "signature_data" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSignatureData() {
    signatureData_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataECGEncrypt);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataECGEncrypt other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(HisEcg, other.HisEcg)) return false;
    if (SignatureData != other.SignatureData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasHisEcg) hash ^= HisEcg.GetHashCode();
    if (HasSignatureData) hash ^= SignatureData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasHisEcg) {
      output.WriteRawTag(10);
      output.WriteMessage(HisEcg);
    }
    if (HasSignatureData) {
      output.WriteRawTag(18);
      output.WriteBytes(SignatureData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasHisEcg) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(HisEcg);
    }
    if (HasSignatureData) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(SignatureData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataECGEncrypt other) {
    if (other == null) {
      return;
    }
    if (other.HasHisEcg) {
      if (!HasHisEcg) {
        HisEcg = new global::HisECGEncrypt();
      }
      HisEcg.MergeFrom(other.HisEcg);
    }
    if (other.HasSignatureData) {
      SignatureData = other.SignatureData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasHisEcg) {
            HisEcg = new global::HisECGEncrypt();
          }
          input.ReadMessage(HisEcg);
          break;
        }
        case 18: {
          SignatureData = input.ReadBytes();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
