// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: his_ecg_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from his_ecg_data.proto</summary>
public static partial class HisEcgDataReflection {

  #region Descriptor
  /// <summary>File descriptor for his_ecg_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HisEcgDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJoaXNfZWNnX2RhdGEucHJvdG8aE3JlYWx0aW1lX2RhdGEucHJvdG8iQQoK",
          "SGlzRGF0YUVDRxIdCgp0aW1lX3N0YW1wGAEgAigLMgkuRGF0ZVRpbWUSFAoI",
          "cmF3X2RhdGEYAiADKA9CAhABQglaBy4vaXdvd24="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataECG), global::HisDataECG.Parser, new[]{ "TimeStamp", "RawData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HisDataECG : pb::IMessage<HisDataECG> {
  private static readonly pb::MessageParser<HisDataECG> _parser = new pb::MessageParser<HisDataECG>(() => new HisDataECG());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataECG> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisEcgDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataECG() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataECG(HisDataECG other) : this() {
    timeStamp_ = other.HasTimeStamp ? other.timeStamp_.Clone() : null;
    rawData_ = other.rawData_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataECG Clone() {
    return new HisDataECG(this);
  }

  /// <summary>Field number for the "time_stamp" field.</summary>
  public const int TimeStampFieldNumber = 1;
  private global::DateTime timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the time_stamp field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTimeStamp {
    get { return timeStamp_ != null; }
  }
  /// <summary>Clears the value of the time_stamp field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimeStamp() {
    timeStamp_ = null;
  }

  /// <summary>Field number for the "raw_data" field.</summary>
  public const int RawDataFieldNumber = 2;
  private static readonly pb::FieldCodec<int> _repeated_rawData_codec
      = pb::FieldCodec.ForSFixed32(18);
  private readonly pbc::RepeatedField<int> rawData_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<int> RawData {
    get { return rawData_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataECG);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataECG other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
    if(!rawData_.Equals(other.rawData_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    hash ^= rawData_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTimeStamp) {
      output.WriteRawTag(10);
      output.WriteMessage(TimeStamp);
    }
    rawData_.WriteTo(output, _repeated_rawData_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
    }
    size += rawData_.CalculateSize(_repeated_rawData_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataECG other) {
    if (other == null) {
      return;
    }
    if (other.HasTimeStamp) {
      if (!HasTimeStamp) {
        TimeStamp = new global::DateTime();
      }
      TimeStamp.MergeFrom(other.TimeStamp);
    }
    rawData_.Add(other.rawData_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTimeStamp) {
            TimeStamp = new global::DateTime();
          }
          input.ReadMessage(TimeStamp);
          break;
        }
        case 18:
        case 21: {
          rawData_.AddEntriesFrom(input, _repeated_rawData_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
