// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: his_gnss_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from his_gnss_data.proto</summary>
public static partial class HisGnssDataReflection {

  #region Descriptor
  /// <summary>File descriptor for his_gnss_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HisGnssDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNoaXNfZ25zc19kYXRhLnByb3RvGhNyZWFsdGltZV9kYXRhLnByb3RvIlYK",
          "C0hpc0RhdGFHTlNTEh0KCnRpbWVfc3RhbXAYASACKAsyCS5EYXRlVGltZRIR",
          "CglmcmVxdWVuY3kYAiACKAcSFQoEZ25zcxgDIAMoCzIHLlJ0R05TU0IJWgcu",
          "L2l3b3du"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataGNSS), global::HisDataGNSS.Parser, new[]{ "TimeStamp", "Frequency", "Gnss" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HisDataGNSS : pb::IMessage<HisDataGNSS> {
  private static readonly pb::MessageParser<HisDataGNSS> _parser = new pb::MessageParser<HisDataGNSS>(() => new HisDataGNSS());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataGNSS> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisGnssDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataGNSS() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataGNSS(HisDataGNSS other) : this() {
    _hasBits0 = other._hasBits0;
    timeStamp_ = other.HasTimeStamp ? other.timeStamp_.Clone() : null;
    frequency_ = other.frequency_;
    gnss_ = other.gnss_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataGNSS Clone() {
    return new HisDataGNSS(this);
  }

  /// <summary>Field number for the "time_stamp" field.</summary>
  public const int TimeStampFieldNumber = 1;
  private global::DateTime timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the time_stamp field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTimeStamp {
    get { return timeStamp_ != null; }
  }
  /// <summary>Clears the value of the time_stamp field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimeStamp() {
    timeStamp_ = null;
  }

  /// <summary>Field number for the "frequency" field.</summary>
  public const int FrequencyFieldNumber = 2;
  private readonly static uint FrequencyDefaultValue = 0;

  private uint frequency_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Frequency {
    get { if ((_hasBits0 & 1) != 0) { return frequency_; } else { return FrequencyDefaultValue; } }
    set {
      _hasBits0 |= 1;
      frequency_ = value;
    }
  }
  /// <summary>Gets whether the "frequency" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasFrequency {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "frequency" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearFrequency() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "gnss" field.</summary>
  public const int GnssFieldNumber = 3;
  private static readonly pb::FieldCodec<global::RtGNSS> _repeated_gnss_codec
      = pb::FieldCodec.ForMessage(26, global::RtGNSS.Parser);
  private readonly pbc::RepeatedField<global::RtGNSS> gnss_ = new pbc::RepeatedField<global::RtGNSS>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::RtGNSS> Gnss {
    get { return gnss_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataGNSS);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataGNSS other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
    if (Frequency != other.Frequency) return false;
    if(!gnss_.Equals(other.gnss_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    if (HasFrequency) hash ^= Frequency.GetHashCode();
    hash ^= gnss_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTimeStamp) {
      output.WriteRawTag(10);
      output.WriteMessage(TimeStamp);
    }
    if (HasFrequency) {
      output.WriteRawTag(21);
      output.WriteFixed32(Frequency);
    }
    gnss_.WriteTo(output, _repeated_gnss_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
    }
    if (HasFrequency) {
      size += 1 + 4;
    }
    size += gnss_.CalculateSize(_repeated_gnss_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataGNSS other) {
    if (other == null) {
      return;
    }
    if (other.HasTimeStamp) {
      if (!HasTimeStamp) {
        TimeStamp = new global::DateTime();
      }
      TimeStamp.MergeFrom(other.TimeStamp);
    }
    if (other.HasFrequency) {
      Frequency = other.Frequency;
    }
    gnss_.Add(other.gnss_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTimeStamp) {
            TimeStamp = new global::DateTime();
          }
          input.ReadMessage(TimeStamp);
          break;
        }
        case 21: {
          Frequency = input.ReadFixed32();
          break;
        }
        case 26: {
          gnss_.AddEntriesFrom(input, _repeated_gnss_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
