// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: his_medic_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from his_medic_data.proto</summary>
public static partial class HisMedicDataReflection {

  #region Descriptor
  /// <summary>File descriptor for his_medic_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HisMedicDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRoaXNfbWVkaWNfZGF0YS5wcm90bxoTcmVhbHRpbWVfZGF0YS5wcm90byKB",
          "AQoMSGlzRGF0YU1lZGljEh0KCnRpbWVfc3RhbXAYASACKAsyCS5EYXRlVGlt",
          "ZRISCgpwYWluX2xldmVsGAIgASgHEhUKDWZhdGlndWVfbGV2ZWwYAyABKAcS",
          "EwoLc3RpZmZfbGV2ZWwYBCABKAcSEgoKc3RpZmZfdGltZRgFIAEoB0IJWgcu",
          "L2l3b3du"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataMedic), global::HisDataMedic.Parser, new[]{ "TimeStamp", "PainLevel", "FatigueLevel", "StiffLevel", "StiffTime" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HisDataMedic : pb::IMessage<HisDataMedic> {
  private static readonly pb::MessageParser<HisDataMedic> _parser = new pb::MessageParser<HisDataMedic>(() => new HisDataMedic());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataMedic> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisMedicDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataMedic() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataMedic(HisDataMedic other) : this() {
    _hasBits0 = other._hasBits0;
    timeStamp_ = other.HasTimeStamp ? other.timeStamp_.Clone() : null;
    painLevel_ = other.painLevel_;
    fatigueLevel_ = other.fatigueLevel_;
    stiffLevel_ = other.stiffLevel_;
    stiffTime_ = other.stiffTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataMedic Clone() {
    return new HisDataMedic(this);
  }

  /// <summary>Field number for the "time_stamp" field.</summary>
  public const int TimeStampFieldNumber = 1;
  private global::DateTime timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the time_stamp field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTimeStamp {
    get { return timeStamp_ != null; }
  }
  /// <summary>Clears the value of the time_stamp field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimeStamp() {
    timeStamp_ = null;
  }

  /// <summary>Field number for the "pain_level" field.</summary>
  public const int PainLevelFieldNumber = 2;
  private readonly static uint PainLevelDefaultValue = 0;

  private uint painLevel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint PainLevel {
    get { if ((_hasBits0 & 1) != 0) { return painLevel_; } else { return PainLevelDefaultValue; } }
    set {
      _hasBits0 |= 1;
      painLevel_ = value;
    }
  }
  /// <summary>Gets whether the "pain_level" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPainLevel {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "pain_level" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPainLevel() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "fatigue_level" field.</summary>
  public const int FatigueLevelFieldNumber = 3;
  private readonly static uint FatigueLevelDefaultValue = 0;

  private uint fatigueLevel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint FatigueLevel {
    get { if ((_hasBits0 & 2) != 0) { return fatigueLevel_; } else { return FatigueLevelDefaultValue; } }
    set {
      _hasBits0 |= 2;
      fatigueLevel_ = value;
    }
  }
  /// <summary>Gets whether the "fatigue_level" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasFatigueLevel {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "fatigue_level" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearFatigueLevel() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "stiff_level" field.</summary>
  public const int StiffLevelFieldNumber = 4;
  private readonly static uint StiffLevelDefaultValue = 0;

  private uint stiffLevel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint StiffLevel {
    get { if ((_hasBits0 & 4) != 0) { return stiffLevel_; } else { return StiffLevelDefaultValue; } }
    set {
      _hasBits0 |= 4;
      stiffLevel_ = value;
    }
  }
  /// <summary>Gets whether the "stiff_level" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasStiffLevel {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "stiff_level" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearStiffLevel() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "stiff_time" field.</summary>
  public const int StiffTimeFieldNumber = 5;
  private readonly static uint StiffTimeDefaultValue = 0;

  private uint stiffTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint StiffTime {
    get { if ((_hasBits0 & 8) != 0) { return stiffTime_; } else { return StiffTimeDefaultValue; } }
    set {
      _hasBits0 |= 8;
      stiffTime_ = value;
    }
  }
  /// <summary>Gets whether the "stiff_time" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasStiffTime {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "stiff_time" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearStiffTime() {
    _hasBits0 &= ~8;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataMedic);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataMedic other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
    if (PainLevel != other.PainLevel) return false;
    if (FatigueLevel != other.FatigueLevel) return false;
    if (StiffLevel != other.StiffLevel) return false;
    if (StiffTime != other.StiffTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    if (HasPainLevel) hash ^= PainLevel.GetHashCode();
    if (HasFatigueLevel) hash ^= FatigueLevel.GetHashCode();
    if (HasStiffLevel) hash ^= StiffLevel.GetHashCode();
    if (HasStiffTime) hash ^= StiffTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTimeStamp) {
      output.WriteRawTag(10);
      output.WriteMessage(TimeStamp);
    }
    if (HasPainLevel) {
      output.WriteRawTag(21);
      output.WriteFixed32(PainLevel);
    }
    if (HasFatigueLevel) {
      output.WriteRawTag(29);
      output.WriteFixed32(FatigueLevel);
    }
    if (HasStiffLevel) {
      output.WriteRawTag(37);
      output.WriteFixed32(StiffLevel);
    }
    if (HasStiffTime) {
      output.WriteRawTag(45);
      output.WriteFixed32(StiffTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
    }
    if (HasPainLevel) {
      size += 1 + 4;
    }
    if (HasFatigueLevel) {
      size += 1 + 4;
    }
    if (HasStiffLevel) {
      size += 1 + 4;
    }
    if (HasStiffTime) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataMedic other) {
    if (other == null) {
      return;
    }
    if (other.HasTimeStamp) {
      if (!HasTimeStamp) {
        TimeStamp = new global::DateTime();
      }
      TimeStamp.MergeFrom(other.TimeStamp);
    }
    if (other.HasPainLevel) {
      PainLevel = other.PainLevel;
    }
    if (other.HasFatigueLevel) {
      FatigueLevel = other.FatigueLevel;
    }
    if (other.HasStiffLevel) {
      StiffLevel = other.StiffLevel;
    }
    if (other.HasStiffTime) {
      StiffTime = other.StiffTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTimeStamp) {
            TimeStamp = new global::DateTime();
          }
          input.ReadMessage(TimeStamp);
          break;
        }
        case 21: {
          PainLevel = input.ReadFixed32();
          break;
        }
        case 29: {
          FatigueLevel = input.ReadFixed32();
          break;
        }
        case 37: {
          StiffLevel = input.ReadFixed32();
          break;
        }
        case 45: {
          StiffTime = input.ReadFixed32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
