// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: his_temperature_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from his_temperature_data.proto</summary>
public static partial class HisTemperatureDataReflection {

  #region Descriptor
  /// <summary>File descriptor for his_temperature_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HisTemperatureDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpoaXNfdGVtcGVyYXR1cmVfZGF0YS5wcm90bxoTcmVhbHRpbWVfZGF0YS5w",
          "cm90byIwCgpTZW5zb3JUZW1wEhAKCGV2aV9ib2R5GAEgAigHEhAKCGVzdGlf",
          "YXJtGAIgAigHIlUKEkhpc0RhdGFUZW1wZXJhdHVyZRIdCgp0aW1lX3N0YW1w",
          "GAEgAigLMgkuRGF0ZVRpbWUSIAoLdGVtcGVyYXR1cmUYAiACKAsyCy5TZW5z",
          "b3JUZW1wQglaBy4vaXdvd24="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SensorTemp), global::SensorTemp.Parser, new[]{ "EviBody", "EstiArm" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataTemperature), global::HisDataTemperature.Parser, new[]{ "TimeStamp", "Temperature" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SensorTemp : pb::IMessage<SensorTemp> {
  private static readonly pb::MessageParser<SensorTemp> _parser = new pb::MessageParser<SensorTemp>(() => new SensorTemp());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SensorTemp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisTemperatureDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SensorTemp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SensorTemp(SensorTemp other) : this() {
    _hasBits0 = other._hasBits0;
    eviBody_ = other.eviBody_;
    estiArm_ = other.estiArm_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SensorTemp Clone() {
    return new SensorTemp(this);
  }

  /// <summary>Field number for the "evi_body" field.</summary>
  public const int EviBodyFieldNumber = 1;
  private readonly static uint EviBodyDefaultValue = 0;

  private uint eviBody_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint EviBody {
    get { if ((_hasBits0 & 1) != 0) { return eviBody_; } else { return EviBodyDefaultValue; } }
    set {
      _hasBits0 |= 1;
      eviBody_ = value;
    }
  }
  /// <summary>Gets whether the "evi_body" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEviBody {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "evi_body" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEviBody() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "esti_arm" field.</summary>
  public const int EstiArmFieldNumber = 2;
  private readonly static uint EstiArmDefaultValue = 0;

  private uint estiArm_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint EstiArm {
    get { if ((_hasBits0 & 2) != 0) { return estiArm_; } else { return EstiArmDefaultValue; } }
    set {
      _hasBits0 |= 2;
      estiArm_ = value;
    }
  }
  /// <summary>Gets whether the "esti_arm" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEstiArm {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "esti_arm" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEstiArm() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SensorTemp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SensorTemp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EviBody != other.EviBody) return false;
    if (EstiArm != other.EstiArm) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasEviBody) hash ^= EviBody.GetHashCode();
    if (HasEstiArm) hash ^= EstiArm.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasEviBody) {
      output.WriteRawTag(13);
      output.WriteFixed32(EviBody);
    }
    if (HasEstiArm) {
      output.WriteRawTag(21);
      output.WriteFixed32(EstiArm);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasEviBody) {
      size += 1 + 4;
    }
    if (HasEstiArm) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SensorTemp other) {
    if (other == null) {
      return;
    }
    if (other.HasEviBody) {
      EviBody = other.EviBody;
    }
    if (other.HasEstiArm) {
      EstiArm = other.EstiArm;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          EviBody = input.ReadFixed32();
          break;
        }
        case 21: {
          EstiArm = input.ReadFixed32();
          break;
        }
      }
    }
  }

}

public sealed partial class HisDataTemperature : pb::IMessage<HisDataTemperature> {
  private static readonly pb::MessageParser<HisDataTemperature> _parser = new pb::MessageParser<HisDataTemperature>(() => new HisDataTemperature());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataTemperature> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisTemperatureDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataTemperature() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataTemperature(HisDataTemperature other) : this() {
    timeStamp_ = other.HasTimeStamp ? other.timeStamp_.Clone() : null;
    temperature_ = other.HasTemperature ? other.temperature_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataTemperature Clone() {
    return new HisDataTemperature(this);
  }

  /// <summary>Field number for the "time_stamp" field.</summary>
  public const int TimeStampFieldNumber = 1;
  private global::DateTime timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the time_stamp field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTimeStamp {
    get { return timeStamp_ != null; }
  }
  /// <summary>Clears the value of the time_stamp field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimeStamp() {
    timeStamp_ = null;
  }

  /// <summary>Field number for the "temperature" field.</summary>
  public const int TemperatureFieldNumber = 2;
  private global::SensorTemp temperature_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::SensorTemp Temperature {
    get { return temperature_; }
    set {
      temperature_ = value;
    }
  }
  /// <summary>Gets whether the temperature field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTemperature {
    get { return temperature_ != null; }
  }
  /// <summary>Clears the value of the temperature field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTemperature() {
    temperature_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataTemperature);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataTemperature other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
    if (!object.Equals(Temperature, other.Temperature)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    if (HasTemperature) hash ^= Temperature.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTimeStamp) {
      output.WriteRawTag(10);
      output.WriteMessage(TimeStamp);
    }
    if (HasTemperature) {
      output.WriteRawTag(18);
      output.WriteMessage(Temperature);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
    }
    if (HasTemperature) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Temperature);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataTemperature other) {
    if (other == null) {
      return;
    }
    if (other.HasTimeStamp) {
      if (!HasTimeStamp) {
        TimeStamp = new global::DateTime();
      }
      TimeStamp.MergeFrom(other.TimeStamp);
    }
    if (other.HasTemperature) {
      if (!HasTemperature) {
        Temperature = new global::SensorTemp();
      }
      Temperature.MergeFrom(other.Temperature);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTimeStamp) {
            TimeStamp = new global::DateTime();
          }
          input.ReadMessage(TimeStamp);
          break;
        }
        case 18: {
          if (!HasTemperature) {
            Temperature = new global::SensorTemp();
          }
          input.ReadMessage(Temperature);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
