// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThirdParty_health_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThirdParty_health_data.proto</summary>
public static partial class ThirdPartyHealthDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ThirdParty_health_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThirdPartyHealthDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChxUaGlyZFBhcnR5X2hlYWx0aF9kYXRhLnByb3RvGhNyZWFsdGltZV9kYXRh",
          "LnByb3RvIn8KElRoaXJkUGFydHlIZWFsdGhCcBILCgNzYnAYASACKAcSCwoD",
          "ZGJwGAIgAigHEgoKAmhyGAMgAigHEg0KBXB1bHNlGAQgAigHEhcKBHRpbWUY",
          "BSACKAsyCS5EYXRlVGltZRIbCgRNT0RFGAYgAigOMg0uTUVBU1VSRV9NT0RF",
          "In8KFVRoaXJkUGFydHlIZWFsdGhTY2FsZRIOCgZ3ZWlnaHQYASACKAcSEQoJ",
          "aW1wZWRhbmNlGAIgAigHEg0KBXVpbnRzGAMgAigHEhsKE2JvZHlfZmF0X3Bl",
          "cmNlbnRhZ2UYBCACKAcSFwoEdGltZRgFIAIoCzIJLkRhdGVUaW1lIlYKFFRo",
          "aXJkUGFydHlIZWFsdGhTcG8yEgsKA2JwbRgBIAIoBxIMCgRzcG8yGAIgAigH",
          "EgoKAnBpGAMgAigHEhcKBHRpbWUYBCACKAsyCS5EYXRlVGltZSJCChRUaGly",
          "ZFBhcnR5SGVhbHRoVGVtcBIRCglib2R5X3RlbXAYASACKAcSFwoEdGltZRgC",
          "IAIoCzIJLkRhdGVUaW1lIjsKE1RoaXJkUGFydHlIZWFsdGhHbHUSCwoDZ2x1",
          "GAEgAigHEhcKBHRpbWUYAiACKAsyCS5EYXRlVGltZSJNChxUaGlyZFBhcnR5",
          "SGVhbHRoQmxvb2RLZXRvbmVzEhQKDEJsb29kS2V0b25lcxgBIAIoBxIXCgR0",
          "aW1lGAIgAigLMgkuRGF0ZVRpbWUiRQoYVGhpcmRQYXJ0eUhlYWx0aFVyaWNB",
          "Y2lkEhAKCFVyaWNBY2lkGAEgAigHEhcKBHRpbWUYAiACKAsyCS5EYXRlVGlt",
          "ZSKUAwoUVGhpcmRQYXJ0eURhdGFIZWFsdGgSEAoIZGV2X25hbWUYASACKAkS",
          "EAoIbWFjX2FkZHIYAiACKAkSEAoIZGV2X3R5cGUYAyACKAcSDAoEdXNlchgE",
          "IAIoBxIkCgdicF9kYXRhGAUgASgLMhMuVGhpcmRQYXJ0eUhlYWx0aEJwEioK",
          "CnNjYWxlX2RhdGEYBiABKAsyFi5UaGlyZFBhcnR5SGVhbHRoU2NhbGUSKAoJ",
          "U3BvMl9kYXRhGAcgASgLMhUuVGhpcmRQYXJ0eUhlYWx0aFNwbzISKAoJVGVt",
          "cF9kYXRhGAggASgLMhUuVGhpcmRQYXJ0eUhlYWx0aFRlbXASJgoIR2x1X2Rh",
          "dGEYCSABKAsyFC5UaGlyZFBhcnR5SGVhbHRoR2x1EjgKEUJsb29kS2V0b25l",
          "c19kYXRhGAogASgLMh0uVGhpcmRQYXJ0eUhlYWx0aEJsb29kS2V0b25lcxIw",
          "Cg1VcmljQWNpZF9kYXRhGAsgASgLMhkuVGhpcmRQYXJ0eUhlYWx0aFVyaWNB",
          "Y2lkIj4KEUhpc0RhdGFUaGlyZFBhcnR5EikKCkRhdGFIZWFsdGgYASABKAsy",
          "FS5UaGlyZFBhcnR5RGF0YUhlYWx0aCokCgxNRUFTVVJFX01PREUSCgoGTUFO",
          "VUFMEAASCAoEQVVUTxABQglaBy4vaXdvd24="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MEASURE_MODE), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThirdPartyHealthBp), global::ThirdPartyHealthBp.Parser, new[]{ "Sbp", "Dbp", "Hr", "Pulse", "Time", "MODE" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThirdPartyHealthScale), global::ThirdPartyHealthScale.Parser, new[]{ "Weight", "Impedance", "Uints", "BodyFatPercentage", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThirdPartyHealthSpo2), global::ThirdPartyHealthSpo2.Parser, new[]{ "Bpm", "Spo2", "Pi", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThirdPartyHealthTemp), global::ThirdPartyHealthTemp.Parser, new[]{ "BodyTemp", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThirdPartyHealthGlu), global::ThirdPartyHealthGlu.Parser, new[]{ "Glu", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThirdPartyHealthBloodKetones), global::ThirdPartyHealthBloodKetones.Parser, new[]{ "BloodKetones", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThirdPartyHealthUricAcid), global::ThirdPartyHealthUricAcid.Parser, new[]{ "UricAcid", "Time" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThirdPartyDataHealth), global::ThirdPartyDataHealth.Parser, new[]{ "DevName", "MacAddr", "DevType", "User", "BpData", "ScaleData", "Spo2Data", "TempData", "GluData", "BloodKetonesData", "UricAcidData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataThirdParty), global::HisDataThirdParty.Parser, new[]{ "DataHealth" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum MEASURE_MODE {
  [pbr::OriginalName("MANUAL")] Manual = 0,
  [pbr::OriginalName("AUTO")] Auto = 1,
}

#endregion

#region Messages
public sealed partial class ThirdPartyHealthBp : pb::IMessage<ThirdPartyHealthBp> {
  private static readonly pb::MessageParser<ThirdPartyHealthBp> _parser = new pb::MessageParser<ThirdPartyHealthBp>(() => new ThirdPartyHealthBp());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ThirdPartyHealthBp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthBp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthBp(ThirdPartyHealthBp other) : this() {
    _hasBits0 = other._hasBits0;
    sbp_ = other.sbp_;
    dbp_ = other.dbp_;
    hr_ = other.hr_;
    pulse_ = other.pulse_;
    time_ = other.HasTime ? other.time_.Clone() : null;
    mODE_ = other.mODE_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthBp Clone() {
    return new ThirdPartyHealthBp(this);
  }

  /// <summary>Field number for the "sbp" field.</summary>
  public const int SbpFieldNumber = 1;
  private readonly static uint SbpDefaultValue = 0;

  private uint sbp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Sbp {
    get { if ((_hasBits0 & 1) != 0) { return sbp_; } else { return SbpDefaultValue; } }
    set {
      _hasBits0 |= 1;
      sbp_ = value;
    }
  }
  /// <summary>Gets whether the "sbp" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSbp {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "sbp" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSbp() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "dbp" field.</summary>
  public const int DbpFieldNumber = 2;
  private readonly static uint DbpDefaultValue = 0;

  private uint dbp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Dbp {
    get { if ((_hasBits0 & 2) != 0) { return dbp_; } else { return DbpDefaultValue; } }
    set {
      _hasBits0 |= 2;
      dbp_ = value;
    }
  }
  /// <summary>Gets whether the "dbp" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDbp {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "dbp" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDbp() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "hr" field.</summary>
  public const int HrFieldNumber = 3;
  private readonly static uint HrDefaultValue = 0;

  private uint hr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Hr {
    get { if ((_hasBits0 & 4) != 0) { return hr_; } else { return HrDefaultValue; } }
    set {
      _hasBits0 |= 4;
      hr_ = value;
    }
  }
  /// <summary>Gets whether the "hr" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasHr {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "hr" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearHr() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "pulse" field.</summary>
  public const int PulseFieldNumber = 4;
  private readonly static uint PulseDefaultValue = 0;

  private uint pulse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Pulse {
    get { if ((_hasBits0 & 8) != 0) { return pulse_; } else { return PulseDefaultValue; } }
    set {
      _hasBits0 |= 8;
      pulse_ = value;
    }
  }
  /// <summary>Gets whether the "pulse" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPulse {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "pulse" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPulse() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 5;
  private global::DateTime time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }
  /// <summary>Gets whether the time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTime() {
    time_ = null;
  }

  /// <summary>Field number for the "MODE" field.</summary>
  public const int MODEFieldNumber = 6;
  private readonly static global::MEASURE_MODE MODEDefaultValue = global::MEASURE_MODE.Manual;

  private global::MEASURE_MODE mODE_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::MEASURE_MODE MODE {
    get { if ((_hasBits0 & 16) != 0) { return mODE_; } else { return MODEDefaultValue; } }
    set {
      _hasBits0 |= 16;
      mODE_ = value;
    }
  }
  /// <summary>Gets whether the "MODE" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMODE {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "MODE" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMODE() {
    _hasBits0 &= ~16;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ThirdPartyHealthBp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ThirdPartyHealthBp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Sbp != other.Sbp) return false;
    if (Dbp != other.Dbp) return false;
    if (Hr != other.Hr) return false;
    if (Pulse != other.Pulse) return false;
    if (!object.Equals(Time, other.Time)) return false;
    if (MODE != other.MODE) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasSbp) hash ^= Sbp.GetHashCode();
    if (HasDbp) hash ^= Dbp.GetHashCode();
    if (HasHr) hash ^= Hr.GetHashCode();
    if (HasPulse) hash ^= Pulse.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (HasMODE) hash ^= MODE.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasSbp) {
      output.WriteRawTag(13);
      output.WriteFixed32(Sbp);
    }
    if (HasDbp) {
      output.WriteRawTag(21);
      output.WriteFixed32(Dbp);
    }
    if (HasHr) {
      output.WriteRawTag(29);
      output.WriteFixed32(Hr);
    }
    if (HasPulse) {
      output.WriteRawTag(37);
      output.WriteFixed32(Pulse);
    }
    if (HasTime) {
      output.WriteRawTag(42);
      output.WriteMessage(Time);
    }
    if (HasMODE) {
      output.WriteRawTag(48);
      output.WriteEnum((int) MODE);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasSbp) {
      size += 1 + 4;
    }
    if (HasDbp) {
      size += 1 + 4;
    }
    if (HasHr) {
      size += 1 + 4;
    }
    if (HasPulse) {
      size += 1 + 4;
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
    }
    if (HasMODE) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MODE);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ThirdPartyHealthBp other) {
    if (other == null) {
      return;
    }
    if (other.HasSbp) {
      Sbp = other.Sbp;
    }
    if (other.HasDbp) {
      Dbp = other.Dbp;
    }
    if (other.HasHr) {
      Hr = other.Hr;
    }
    if (other.HasPulse) {
      Pulse = other.Pulse;
    }
    if (other.HasTime) {
      if (!HasTime) {
        Time = new global::DateTime();
      }
      Time.MergeFrom(other.Time);
    }
    if (other.HasMODE) {
      MODE = other.MODE;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          Sbp = input.ReadFixed32();
          break;
        }
        case 21: {
          Dbp = input.ReadFixed32();
          break;
        }
        case 29: {
          Hr = input.ReadFixed32();
          break;
        }
        case 37: {
          Pulse = input.ReadFixed32();
          break;
        }
        case 42: {
          if (!HasTime) {
            Time = new global::DateTime();
          }
          input.ReadMessage(Time);
          break;
        }
        case 48: {
          MODE = (global::MEASURE_MODE) input.ReadEnum();
          break;
        }
      }
    }
  }

}

public sealed partial class ThirdPartyHealthScale : pb::IMessage<ThirdPartyHealthScale> {
  private static readonly pb::MessageParser<ThirdPartyHealthScale> _parser = new pb::MessageParser<ThirdPartyHealthScale>(() => new ThirdPartyHealthScale());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ThirdPartyHealthScale> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthScale() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthScale(ThirdPartyHealthScale other) : this() {
    _hasBits0 = other._hasBits0;
    weight_ = other.weight_;
    impedance_ = other.impedance_;
    uints_ = other.uints_;
    bodyFatPercentage_ = other.bodyFatPercentage_;
    time_ = other.HasTime ? other.time_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthScale Clone() {
    return new ThirdPartyHealthScale(this);
  }

  /// <summary>Field number for the "weight" field.</summary>
  public const int WeightFieldNumber = 1;
  private readonly static uint WeightDefaultValue = 0;

  private uint weight_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Weight {
    get { if ((_hasBits0 & 1) != 0) { return weight_; } else { return WeightDefaultValue; } }
    set {
      _hasBits0 |= 1;
      weight_ = value;
    }
  }
  /// <summary>Gets whether the "weight" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasWeight {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "weight" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearWeight() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "impedance" field.</summary>
  public const int ImpedanceFieldNumber = 2;
  private readonly static uint ImpedanceDefaultValue = 0;

  private uint impedance_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Impedance {
    get { if ((_hasBits0 & 2) != 0) { return impedance_; } else { return ImpedanceDefaultValue; } }
    set {
      _hasBits0 |= 2;
      impedance_ = value;
    }
  }
  /// <summary>Gets whether the "impedance" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasImpedance {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "impedance" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearImpedance() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "uints" field.</summary>
  public const int UintsFieldNumber = 3;
  private readonly static uint UintsDefaultValue = 0;

  private uint uints_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Uints {
    get { if ((_hasBits0 & 4) != 0) { return uints_; } else { return UintsDefaultValue; } }
    set {
      _hasBits0 |= 4;
      uints_ = value;
    }
  }
  /// <summary>Gets whether the "uints" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasUints {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "uints" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearUints() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "body_fat_percentage" field.</summary>
  public const int BodyFatPercentageFieldNumber = 4;
  private readonly static uint BodyFatPercentageDefaultValue = 0;

  private uint bodyFatPercentage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint BodyFatPercentage {
    get { if ((_hasBits0 & 8) != 0) { return bodyFatPercentage_; } else { return BodyFatPercentageDefaultValue; } }
    set {
      _hasBits0 |= 8;
      bodyFatPercentage_ = value;
    }
  }
  /// <summary>Gets whether the "body_fat_percentage" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBodyFatPercentage {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "body_fat_percentage" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBodyFatPercentage() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 5;
  private global::DateTime time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }
  /// <summary>Gets whether the time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTime() {
    time_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ThirdPartyHealthScale);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ThirdPartyHealthScale other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Weight != other.Weight) return false;
    if (Impedance != other.Impedance) return false;
    if (Uints != other.Uints) return false;
    if (BodyFatPercentage != other.BodyFatPercentage) return false;
    if (!object.Equals(Time, other.Time)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasWeight) hash ^= Weight.GetHashCode();
    if (HasImpedance) hash ^= Impedance.GetHashCode();
    if (HasUints) hash ^= Uints.GetHashCode();
    if (HasBodyFatPercentage) hash ^= BodyFatPercentage.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasWeight) {
      output.WriteRawTag(13);
      output.WriteFixed32(Weight);
    }
    if (HasImpedance) {
      output.WriteRawTag(21);
      output.WriteFixed32(Impedance);
    }
    if (HasUints) {
      output.WriteRawTag(29);
      output.WriteFixed32(Uints);
    }
    if (HasBodyFatPercentage) {
      output.WriteRawTag(37);
      output.WriteFixed32(BodyFatPercentage);
    }
    if (HasTime) {
      output.WriteRawTag(42);
      output.WriteMessage(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasWeight) {
      size += 1 + 4;
    }
    if (HasImpedance) {
      size += 1 + 4;
    }
    if (HasUints) {
      size += 1 + 4;
    }
    if (HasBodyFatPercentage) {
      size += 1 + 4;
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ThirdPartyHealthScale other) {
    if (other == null) {
      return;
    }
    if (other.HasWeight) {
      Weight = other.Weight;
    }
    if (other.HasImpedance) {
      Impedance = other.Impedance;
    }
    if (other.HasUints) {
      Uints = other.Uints;
    }
    if (other.HasBodyFatPercentage) {
      BodyFatPercentage = other.BodyFatPercentage;
    }
    if (other.HasTime) {
      if (!HasTime) {
        Time = new global::DateTime();
      }
      Time.MergeFrom(other.Time);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          Weight = input.ReadFixed32();
          break;
        }
        case 21: {
          Impedance = input.ReadFixed32();
          break;
        }
        case 29: {
          Uints = input.ReadFixed32();
          break;
        }
        case 37: {
          BodyFatPercentage = input.ReadFixed32();
          break;
        }
        case 42: {
          if (!HasTime) {
            Time = new global::DateTime();
          }
          input.ReadMessage(Time);
          break;
        }
      }
    }
  }

}

public sealed partial class ThirdPartyHealthSpo2 : pb::IMessage<ThirdPartyHealthSpo2> {
  private static readonly pb::MessageParser<ThirdPartyHealthSpo2> _parser = new pb::MessageParser<ThirdPartyHealthSpo2>(() => new ThirdPartyHealthSpo2());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ThirdPartyHealthSpo2> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthSpo2() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthSpo2(ThirdPartyHealthSpo2 other) : this() {
    _hasBits0 = other._hasBits0;
    bpm_ = other.bpm_;
    spo2_ = other.spo2_;
    pi_ = other.pi_;
    time_ = other.HasTime ? other.time_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthSpo2 Clone() {
    return new ThirdPartyHealthSpo2(this);
  }

  /// <summary>Field number for the "bpm" field.</summary>
  public const int BpmFieldNumber = 1;
  private readonly static uint BpmDefaultValue = 0;

  private uint bpm_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Bpm {
    get { if ((_hasBits0 & 1) != 0) { return bpm_; } else { return BpmDefaultValue; } }
    set {
      _hasBits0 |= 1;
      bpm_ = value;
    }
  }
  /// <summary>Gets whether the "bpm" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBpm {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "bpm" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBpm() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "spo2" field.</summary>
  public const int Spo2FieldNumber = 2;
  private readonly static uint Spo2DefaultValue = 0;

  private uint spo2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Spo2 {
    get { if ((_hasBits0 & 2) != 0) { return spo2_; } else { return Spo2DefaultValue; } }
    set {
      _hasBits0 |= 2;
      spo2_ = value;
    }
  }
  /// <summary>Gets whether the "spo2" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSpo2 {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "spo2" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSpo2() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "pi" field.</summary>
  public const int PiFieldNumber = 3;
  private readonly static uint PiDefaultValue = 0;

  private uint pi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Pi {
    get { if ((_hasBits0 & 4) != 0) { return pi_; } else { return PiDefaultValue; } }
    set {
      _hasBits0 |= 4;
      pi_ = value;
    }
  }
  /// <summary>Gets whether the "pi" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPi {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "pi" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPi() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 4;
  private global::DateTime time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }
  /// <summary>Gets whether the time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTime() {
    time_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ThirdPartyHealthSpo2);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ThirdPartyHealthSpo2 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Bpm != other.Bpm) return false;
    if (Spo2 != other.Spo2) return false;
    if (Pi != other.Pi) return false;
    if (!object.Equals(Time, other.Time)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasBpm) hash ^= Bpm.GetHashCode();
    if (HasSpo2) hash ^= Spo2.GetHashCode();
    if (HasPi) hash ^= Pi.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasBpm) {
      output.WriteRawTag(13);
      output.WriteFixed32(Bpm);
    }
    if (HasSpo2) {
      output.WriteRawTag(21);
      output.WriteFixed32(Spo2);
    }
    if (HasPi) {
      output.WriteRawTag(29);
      output.WriteFixed32(Pi);
    }
    if (HasTime) {
      output.WriteRawTag(34);
      output.WriteMessage(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasBpm) {
      size += 1 + 4;
    }
    if (HasSpo2) {
      size += 1 + 4;
    }
    if (HasPi) {
      size += 1 + 4;
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ThirdPartyHealthSpo2 other) {
    if (other == null) {
      return;
    }
    if (other.HasBpm) {
      Bpm = other.Bpm;
    }
    if (other.HasSpo2) {
      Spo2 = other.Spo2;
    }
    if (other.HasPi) {
      Pi = other.Pi;
    }
    if (other.HasTime) {
      if (!HasTime) {
        Time = new global::DateTime();
      }
      Time.MergeFrom(other.Time);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          Bpm = input.ReadFixed32();
          break;
        }
        case 21: {
          Spo2 = input.ReadFixed32();
          break;
        }
        case 29: {
          Pi = input.ReadFixed32();
          break;
        }
        case 34: {
          if (!HasTime) {
            Time = new global::DateTime();
          }
          input.ReadMessage(Time);
          break;
        }
      }
    }
  }

}

public sealed partial class ThirdPartyHealthTemp : pb::IMessage<ThirdPartyHealthTemp> {
  private static readonly pb::MessageParser<ThirdPartyHealthTemp> _parser = new pb::MessageParser<ThirdPartyHealthTemp>(() => new ThirdPartyHealthTemp());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ThirdPartyHealthTemp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthTemp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthTemp(ThirdPartyHealthTemp other) : this() {
    _hasBits0 = other._hasBits0;
    bodyTemp_ = other.bodyTemp_;
    time_ = other.HasTime ? other.time_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthTemp Clone() {
    return new ThirdPartyHealthTemp(this);
  }

  /// <summary>Field number for the "body_temp" field.</summary>
  public const int BodyTempFieldNumber = 1;
  private readonly static uint BodyTempDefaultValue = 0;

  private uint bodyTemp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint BodyTemp {
    get { if ((_hasBits0 & 1) != 0) { return bodyTemp_; } else { return BodyTempDefaultValue; } }
    set {
      _hasBits0 |= 1;
      bodyTemp_ = value;
    }
  }
  /// <summary>Gets whether the "body_temp" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBodyTemp {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "body_temp" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBodyTemp() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private global::DateTime time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }
  /// <summary>Gets whether the time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTime() {
    time_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ThirdPartyHealthTemp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ThirdPartyHealthTemp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (BodyTemp != other.BodyTemp) return false;
    if (!object.Equals(Time, other.Time)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasBodyTemp) hash ^= BodyTemp.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasBodyTemp) {
      output.WriteRawTag(13);
      output.WriteFixed32(BodyTemp);
    }
    if (HasTime) {
      output.WriteRawTag(18);
      output.WriteMessage(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasBodyTemp) {
      size += 1 + 4;
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ThirdPartyHealthTemp other) {
    if (other == null) {
      return;
    }
    if (other.HasBodyTemp) {
      BodyTemp = other.BodyTemp;
    }
    if (other.HasTime) {
      if (!HasTime) {
        Time = new global::DateTime();
      }
      Time.MergeFrom(other.Time);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          BodyTemp = input.ReadFixed32();
          break;
        }
        case 18: {
          if (!HasTime) {
            Time = new global::DateTime();
          }
          input.ReadMessage(Time);
          break;
        }
      }
    }
  }

}

public sealed partial class ThirdPartyHealthGlu : pb::IMessage<ThirdPartyHealthGlu> {
  private static readonly pb::MessageParser<ThirdPartyHealthGlu> _parser = new pb::MessageParser<ThirdPartyHealthGlu>(() => new ThirdPartyHealthGlu());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ThirdPartyHealthGlu> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthGlu() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthGlu(ThirdPartyHealthGlu other) : this() {
    _hasBits0 = other._hasBits0;
    glu_ = other.glu_;
    time_ = other.HasTime ? other.time_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthGlu Clone() {
    return new ThirdPartyHealthGlu(this);
  }

  /// <summary>Field number for the "glu" field.</summary>
  public const int GluFieldNumber = 1;
  private readonly static uint GluDefaultValue = 0;

  private uint glu_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Glu {
    get { if ((_hasBits0 & 1) != 0) { return glu_; } else { return GluDefaultValue; } }
    set {
      _hasBits0 |= 1;
      glu_ = value;
    }
  }
  /// <summary>Gets whether the "glu" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGlu {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "glu" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGlu() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private global::DateTime time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }
  /// <summary>Gets whether the time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTime() {
    time_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ThirdPartyHealthGlu);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ThirdPartyHealthGlu other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Glu != other.Glu) return false;
    if (!object.Equals(Time, other.Time)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasGlu) hash ^= Glu.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasGlu) {
      output.WriteRawTag(13);
      output.WriteFixed32(Glu);
    }
    if (HasTime) {
      output.WriteRawTag(18);
      output.WriteMessage(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasGlu) {
      size += 1 + 4;
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ThirdPartyHealthGlu other) {
    if (other == null) {
      return;
    }
    if (other.HasGlu) {
      Glu = other.Glu;
    }
    if (other.HasTime) {
      if (!HasTime) {
        Time = new global::DateTime();
      }
      Time.MergeFrom(other.Time);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          Glu = input.ReadFixed32();
          break;
        }
        case 18: {
          if (!HasTime) {
            Time = new global::DateTime();
          }
          input.ReadMessage(Time);
          break;
        }
      }
    }
  }

}

public sealed partial class ThirdPartyHealthBloodKetones : pb::IMessage<ThirdPartyHealthBloodKetones> {
  private static readonly pb::MessageParser<ThirdPartyHealthBloodKetones> _parser = new pb::MessageParser<ThirdPartyHealthBloodKetones>(() => new ThirdPartyHealthBloodKetones());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ThirdPartyHealthBloodKetones> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthBloodKetones() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthBloodKetones(ThirdPartyHealthBloodKetones other) : this() {
    _hasBits0 = other._hasBits0;
    bloodKetones_ = other.bloodKetones_;
    time_ = other.HasTime ? other.time_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthBloodKetones Clone() {
    return new ThirdPartyHealthBloodKetones(this);
  }

  /// <summary>Field number for the "BloodKetones" field.</summary>
  public const int BloodKetonesFieldNumber = 1;
  private readonly static uint BloodKetonesDefaultValue = 0;

  private uint bloodKetones_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint BloodKetones {
    get { if ((_hasBits0 & 1) != 0) { return bloodKetones_; } else { return BloodKetonesDefaultValue; } }
    set {
      _hasBits0 |= 1;
      bloodKetones_ = value;
    }
  }
  /// <summary>Gets whether the "BloodKetones" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBloodKetones {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "BloodKetones" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBloodKetones() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private global::DateTime time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }
  /// <summary>Gets whether the time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTime() {
    time_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ThirdPartyHealthBloodKetones);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ThirdPartyHealthBloodKetones other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (BloodKetones != other.BloodKetones) return false;
    if (!object.Equals(Time, other.Time)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasBloodKetones) hash ^= BloodKetones.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasBloodKetones) {
      output.WriteRawTag(13);
      output.WriteFixed32(BloodKetones);
    }
    if (HasTime) {
      output.WriteRawTag(18);
      output.WriteMessage(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasBloodKetones) {
      size += 1 + 4;
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ThirdPartyHealthBloodKetones other) {
    if (other == null) {
      return;
    }
    if (other.HasBloodKetones) {
      BloodKetones = other.BloodKetones;
    }
    if (other.HasTime) {
      if (!HasTime) {
        Time = new global::DateTime();
      }
      Time.MergeFrom(other.Time);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          BloodKetones = input.ReadFixed32();
          break;
        }
        case 18: {
          if (!HasTime) {
            Time = new global::DateTime();
          }
          input.ReadMessage(Time);
          break;
        }
      }
    }
  }

}

public sealed partial class ThirdPartyHealthUricAcid : pb::IMessage<ThirdPartyHealthUricAcid> {
  private static readonly pb::MessageParser<ThirdPartyHealthUricAcid> _parser = new pb::MessageParser<ThirdPartyHealthUricAcid>(() => new ThirdPartyHealthUricAcid());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ThirdPartyHealthUricAcid> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthUricAcid() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthUricAcid(ThirdPartyHealthUricAcid other) : this() {
    _hasBits0 = other._hasBits0;
    uricAcid_ = other.uricAcid_;
    time_ = other.HasTime ? other.time_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyHealthUricAcid Clone() {
    return new ThirdPartyHealthUricAcid(this);
  }

  /// <summary>Field number for the "UricAcid" field.</summary>
  public const int UricAcidFieldNumber = 1;
  private readonly static uint UricAcidDefaultValue = 0;

  private uint uricAcid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint UricAcid {
    get { if ((_hasBits0 & 1) != 0) { return uricAcid_; } else { return UricAcidDefaultValue; } }
    set {
      _hasBits0 |= 1;
      uricAcid_ = value;
    }
  }
  /// <summary>Gets whether the "UricAcid" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasUricAcid {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "UricAcid" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearUricAcid() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private global::DateTime time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }
  /// <summary>Gets whether the time field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the time field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTime() {
    time_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ThirdPartyHealthUricAcid);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ThirdPartyHealthUricAcid other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UricAcid != other.UricAcid) return false;
    if (!object.Equals(Time, other.Time)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasUricAcid) hash ^= UricAcid.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasUricAcid) {
      output.WriteRawTag(13);
      output.WriteFixed32(UricAcid);
    }
    if (HasTime) {
      output.WriteRawTag(18);
      output.WriteMessage(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasUricAcid) {
      size += 1 + 4;
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ThirdPartyHealthUricAcid other) {
    if (other == null) {
      return;
    }
    if (other.HasUricAcid) {
      UricAcid = other.UricAcid;
    }
    if (other.HasTime) {
      if (!HasTime) {
        Time = new global::DateTime();
      }
      Time.MergeFrom(other.Time);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          UricAcid = input.ReadFixed32();
          break;
        }
        case 18: {
          if (!HasTime) {
            Time = new global::DateTime();
          }
          input.ReadMessage(Time);
          break;
        }
      }
    }
  }

}

public sealed partial class ThirdPartyDataHealth : pb::IMessage<ThirdPartyDataHealth> {
  private static readonly pb::MessageParser<ThirdPartyDataHealth> _parser = new pb::MessageParser<ThirdPartyDataHealth>(() => new ThirdPartyDataHealth());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ThirdPartyDataHealth> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyDataHealth() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyDataHealth(ThirdPartyDataHealth other) : this() {
    _hasBits0 = other._hasBits0;
    devName_ = other.devName_;
    macAddr_ = other.macAddr_;
    devType_ = other.devType_;
    user_ = other.user_;
    bpData_ = other.HasBpData ? other.bpData_.Clone() : null;
    scaleData_ = other.HasScaleData ? other.scaleData_.Clone() : null;
    spo2Data_ = other.HasSpo2Data ? other.spo2Data_.Clone() : null;
    tempData_ = other.HasTempData ? other.tempData_.Clone() : null;
    gluData_ = other.HasGluData ? other.gluData_.Clone() : null;
    bloodKetonesData_ = other.HasBloodKetonesData ? other.bloodKetonesData_.Clone() : null;
    uricAcidData_ = other.HasUricAcidData ? other.uricAcidData_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ThirdPartyDataHealth Clone() {
    return new ThirdPartyDataHealth(this);
  }

  /// <summary>Field number for the "dev_name" field.</summary>
  public const int DevNameFieldNumber = 1;
  private readonly static string DevNameDefaultValue = "";

  private string devName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DevName {
    get { return devName_ ?? DevNameDefaultValue; }
    set {
      devName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "dev_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDevName {
    get { return devName_ != null; }
  }
  /// <summary>Clears the value of the "dev_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDevName() {
    devName_ = null;
  }

  /// <summary>Field number for the "mac_addr" field.</summary>
  public const int MacAddrFieldNumber = 2;
  private readonly static string MacAddrDefaultValue = "";

  private string macAddr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MacAddr {
    get { return macAddr_ ?? MacAddrDefaultValue; }
    set {
      macAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "mac_addr" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMacAddr {
    get { return macAddr_ != null; }
  }
  /// <summary>Clears the value of the "mac_addr" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMacAddr() {
    macAddr_ = null;
  }

  /// <summary>Field number for the "dev_type" field.</summary>
  public const int DevTypeFieldNumber = 3;
  private readonly static uint DevTypeDefaultValue = 0;

  private uint devType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint DevType {
    get { if ((_hasBits0 & 1) != 0) { return devType_; } else { return DevTypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      devType_ = value;
    }
  }
  /// <summary>Gets whether the "dev_type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDevType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "dev_type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDevType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "user" field.</summary>
  public const int UserFieldNumber = 4;
  private readonly static uint UserDefaultValue = 0;

  private uint user_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint User {
    get { if ((_hasBits0 & 2) != 0) { return user_; } else { return UserDefaultValue; } }
    set {
      _hasBits0 |= 2;
      user_ = value;
    }
  }
  /// <summary>Gets whether the "user" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasUser {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "user" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearUser() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "bp_data" field.</summary>
  public const int BpDataFieldNumber = 5;
  private global::ThirdPartyHealthBp bpData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ThirdPartyHealthBp BpData {
    get { return bpData_; }
    set {
      bpData_ = value;
    }
  }
  /// <summary>Gets whether the bp_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBpData {
    get { return bpData_ != null; }
  }
  /// <summary>Clears the value of the bp_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBpData() {
    bpData_ = null;
  }

  /// <summary>Field number for the "scale_data" field.</summary>
  public const int ScaleDataFieldNumber = 6;
  private global::ThirdPartyHealthScale scaleData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ThirdPartyHealthScale ScaleData {
    get { return scaleData_; }
    set {
      scaleData_ = value;
    }
  }
  /// <summary>Gets whether the scale_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasScaleData {
    get { return scaleData_ != null; }
  }
  /// <summary>Clears the value of the scale_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearScaleData() {
    scaleData_ = null;
  }

  /// <summary>Field number for the "Spo2_data" field.</summary>
  public const int Spo2DataFieldNumber = 7;
  private global::ThirdPartyHealthSpo2 spo2Data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ThirdPartyHealthSpo2 Spo2Data {
    get { return spo2Data_; }
    set {
      spo2Data_ = value;
    }
  }
  /// <summary>Gets whether the Spo2_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSpo2Data {
    get { return spo2Data_ != null; }
  }
  /// <summary>Clears the value of the Spo2_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSpo2Data() {
    spo2Data_ = null;
  }

  /// <summary>Field number for the "Temp_data" field.</summary>
  public const int TempDataFieldNumber = 8;
  private global::ThirdPartyHealthTemp tempData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ThirdPartyHealthTemp TempData {
    get { return tempData_; }
    set {
      tempData_ = value;
    }
  }
  /// <summary>Gets whether the Temp_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTempData {
    get { return tempData_ != null; }
  }
  /// <summary>Clears the value of the Temp_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTempData() {
    tempData_ = null;
  }

  /// <summary>Field number for the "Glu_data" field.</summary>
  public const int GluDataFieldNumber = 9;
  private global::ThirdPartyHealthGlu gluData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ThirdPartyHealthGlu GluData {
    get { return gluData_; }
    set {
      gluData_ = value;
    }
  }
  /// <summary>Gets whether the Glu_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGluData {
    get { return gluData_ != null; }
  }
  /// <summary>Clears the value of the Glu_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGluData() {
    gluData_ = null;
  }

  /// <summary>Field number for the "BloodKetones_data" field.</summary>
  public const int BloodKetonesDataFieldNumber = 10;
  private global::ThirdPartyHealthBloodKetones bloodKetonesData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ThirdPartyHealthBloodKetones BloodKetonesData {
    get { return bloodKetonesData_; }
    set {
      bloodKetonesData_ = value;
    }
  }
  /// <summary>Gets whether the BloodKetones_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBloodKetonesData {
    get { return bloodKetonesData_ != null; }
  }
  /// <summary>Clears the value of the BloodKetones_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBloodKetonesData() {
    bloodKetonesData_ = null;
  }

  /// <summary>Field number for the "UricAcid_data" field.</summary>
  public const int UricAcidDataFieldNumber = 11;
  private global::ThirdPartyHealthUricAcid uricAcidData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ThirdPartyHealthUricAcid UricAcidData {
    get { return uricAcidData_; }
    set {
      uricAcidData_ = value;
    }
  }
  /// <summary>Gets whether the UricAcid_data field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasUricAcidData {
    get { return uricAcidData_ != null; }
  }
  /// <summary>Clears the value of the UricAcid_data field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearUricAcidData() {
    uricAcidData_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ThirdPartyDataHealth);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ThirdPartyDataHealth other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DevName != other.DevName) return false;
    if (MacAddr != other.MacAddr) return false;
    if (DevType != other.DevType) return false;
    if (User != other.User) return false;
    if (!object.Equals(BpData, other.BpData)) return false;
    if (!object.Equals(ScaleData, other.ScaleData)) return false;
    if (!object.Equals(Spo2Data, other.Spo2Data)) return false;
    if (!object.Equals(TempData, other.TempData)) return false;
    if (!object.Equals(GluData, other.GluData)) return false;
    if (!object.Equals(BloodKetonesData, other.BloodKetonesData)) return false;
    if (!object.Equals(UricAcidData, other.UricAcidData)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasDevName) hash ^= DevName.GetHashCode();
    if (HasMacAddr) hash ^= MacAddr.GetHashCode();
    if (HasDevType) hash ^= DevType.GetHashCode();
    if (HasUser) hash ^= User.GetHashCode();
    if (HasBpData) hash ^= BpData.GetHashCode();
    if (HasScaleData) hash ^= ScaleData.GetHashCode();
    if (HasSpo2Data) hash ^= Spo2Data.GetHashCode();
    if (HasTempData) hash ^= TempData.GetHashCode();
    if (HasGluData) hash ^= GluData.GetHashCode();
    if (HasBloodKetonesData) hash ^= BloodKetonesData.GetHashCode();
    if (HasUricAcidData) hash ^= UricAcidData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasDevName) {
      output.WriteRawTag(10);
      output.WriteString(DevName);
    }
    if (HasMacAddr) {
      output.WriteRawTag(18);
      output.WriteString(MacAddr);
    }
    if (HasDevType) {
      output.WriteRawTag(29);
      output.WriteFixed32(DevType);
    }
    if (HasUser) {
      output.WriteRawTag(37);
      output.WriteFixed32(User);
    }
    if (HasBpData) {
      output.WriteRawTag(42);
      output.WriteMessage(BpData);
    }
    if (HasScaleData) {
      output.WriteRawTag(50);
      output.WriteMessage(ScaleData);
    }
    if (HasSpo2Data) {
      output.WriteRawTag(58);
      output.WriteMessage(Spo2Data);
    }
    if (HasTempData) {
      output.WriteRawTag(66);
      output.WriteMessage(TempData);
    }
    if (HasGluData) {
      output.WriteRawTag(74);
      output.WriteMessage(GluData);
    }
    if (HasBloodKetonesData) {
      output.WriteRawTag(82);
      output.WriteMessage(BloodKetonesData);
    }
    if (HasUricAcidData) {
      output.WriteRawTag(90);
      output.WriteMessage(UricAcidData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasDevName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DevName);
    }
    if (HasMacAddr) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MacAddr);
    }
    if (HasDevType) {
      size += 1 + 4;
    }
    if (HasUser) {
      size += 1 + 4;
    }
    if (HasBpData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BpData);
    }
    if (HasScaleData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ScaleData);
    }
    if (HasSpo2Data) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spo2Data);
    }
    if (HasTempData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TempData);
    }
    if (HasGluData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(GluData);
    }
    if (HasBloodKetonesData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BloodKetonesData);
    }
    if (HasUricAcidData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UricAcidData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ThirdPartyDataHealth other) {
    if (other == null) {
      return;
    }
    if (other.HasDevName) {
      DevName = other.DevName;
    }
    if (other.HasMacAddr) {
      MacAddr = other.MacAddr;
    }
    if (other.HasDevType) {
      DevType = other.DevType;
    }
    if (other.HasUser) {
      User = other.User;
    }
    if (other.HasBpData) {
      if (!HasBpData) {
        BpData = new global::ThirdPartyHealthBp();
      }
      BpData.MergeFrom(other.BpData);
    }
    if (other.HasScaleData) {
      if (!HasScaleData) {
        ScaleData = new global::ThirdPartyHealthScale();
      }
      ScaleData.MergeFrom(other.ScaleData);
    }
    if (other.HasSpo2Data) {
      if (!HasSpo2Data) {
        Spo2Data = new global::ThirdPartyHealthSpo2();
      }
      Spo2Data.MergeFrom(other.Spo2Data);
    }
    if (other.HasTempData) {
      if (!HasTempData) {
        TempData = new global::ThirdPartyHealthTemp();
      }
      TempData.MergeFrom(other.TempData);
    }
    if (other.HasGluData) {
      if (!HasGluData) {
        GluData = new global::ThirdPartyHealthGlu();
      }
      GluData.MergeFrom(other.GluData);
    }
    if (other.HasBloodKetonesData) {
      if (!HasBloodKetonesData) {
        BloodKetonesData = new global::ThirdPartyHealthBloodKetones();
      }
      BloodKetonesData.MergeFrom(other.BloodKetonesData);
    }
    if (other.HasUricAcidData) {
      if (!HasUricAcidData) {
        UricAcidData = new global::ThirdPartyHealthUricAcid();
      }
      UricAcidData.MergeFrom(other.UricAcidData);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DevName = input.ReadString();
          break;
        }
        case 18: {
          MacAddr = input.ReadString();
          break;
        }
        case 29: {
          DevType = input.ReadFixed32();
          break;
        }
        case 37: {
          User = input.ReadFixed32();
          break;
        }
        case 42: {
          if (!HasBpData) {
            BpData = new global::ThirdPartyHealthBp();
          }
          input.ReadMessage(BpData);
          break;
        }
        case 50: {
          if (!HasScaleData) {
            ScaleData = new global::ThirdPartyHealthScale();
          }
          input.ReadMessage(ScaleData);
          break;
        }
        case 58: {
          if (!HasSpo2Data) {
            Spo2Data = new global::ThirdPartyHealthSpo2();
          }
          input.ReadMessage(Spo2Data);
          break;
        }
        case 66: {
          if (!HasTempData) {
            TempData = new global::ThirdPartyHealthTemp();
          }
          input.ReadMessage(TempData);
          break;
        }
        case 74: {
          if (!HasGluData) {
            GluData = new global::ThirdPartyHealthGlu();
          }
          input.ReadMessage(GluData);
          break;
        }
        case 82: {
          if (!HasBloodKetonesData) {
            BloodKetonesData = new global::ThirdPartyHealthBloodKetones();
          }
          input.ReadMessage(BloodKetonesData);
          break;
        }
        case 90: {
          if (!HasUricAcidData) {
            UricAcidData = new global::ThirdPartyHealthUricAcid();
          }
          input.ReadMessage(UricAcidData);
          break;
        }
      }
    }
  }

}

public sealed partial class HisDataThirdParty : pb::IMessage<HisDataThirdParty> {
  private static readonly pb::MessageParser<HisDataThirdParty> _parser = new pb::MessageParser<HisDataThirdParty>(() => new HisDataThirdParty());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataThirdParty> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThirdPartyHealthDataReflection.Descriptor.MessageTypes[8]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataThirdParty() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataThirdParty(HisDataThirdParty other) : this() {
    dataHealth_ = other.HasDataHealth ? other.dataHealth_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataThirdParty Clone() {
    return new HisDataThirdParty(this);
  }

  /// <summary>Field number for the "DataHealth" field.</summary>
  public const int DataHealthFieldNumber = 1;
  private global::ThirdPartyDataHealth dataHealth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ThirdPartyDataHealth DataHealth {
    get { return dataHealth_; }
    set {
      dataHealth_ = value;
    }
  }
  /// <summary>Gets whether the DataHealth field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDataHealth {
    get { return dataHealth_ != null; }
  }
  /// <summary>Clears the value of the DataHealth field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDataHealth() {
    dataHealth_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataThirdParty);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataThirdParty other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DataHealth, other.DataHealth)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasDataHealth) hash ^= DataHealth.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasDataHealth) {
      output.WriteRawTag(10);
      output.WriteMessage(DataHealth);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasDataHealth) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataHealth);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataThirdParty other) {
    if (other == null) {
      return;
    }
    if (other.HasDataHealth) {
      if (!HasDataHealth) {
        DataHealth = new global::ThirdPartyDataHealth();
      }
      DataHealth.MergeFrom(other.DataHealth);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasDataHealth) {
            DataHealth = new global::ThirdPartyDataHealth();
          }
          input.ReadMessage(DataHealth);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
