// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: yyl_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from yyl_info.proto</summary>
public static partial class YylInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for yyl_info.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static YylInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg55eWxfaW5mby5wcm90byIsCg95eWxfd3VxaV9yZXBvcnQSCgoCd3EYASAC",
          "KAwSDQoFc2NvcmUYAiACKAwiXwoPeXlsX2JvZHlfcmVwb3J0Eg8KB3R6X25h",
          "bWUYASACKAwSEAoIdHpfc2NvcmUYAiACKAwSEwoLcHJlX3R6X25hbWUYAyAC",
          "KAwSFAoMcHJlX3R6X3Njb3JlGAQgAigMIkcKCnl5bF9ub3RpZnkSEgoKaGFz",
          "X3JlcG9ydBgBIAEoCBIlCgtyZXBvcnRfdHlwZRgCIAEoDjIQLnl5bF9yZXBv",
          "cnRfdHlwZSJtCgt5eWxfQ29tbWFuZBIQCghtb2RlbGluZxgBIAEoCBIlCgt3",
          "dXFpX3JlcG9ydBgEIAEoCzIQLnl5bF93dXFpX3JlcG9ydBIlCgtib2R5X3Jl",
          "cG9ydBgFIAEoCzIQLnl5bF9ib2R5X3JlcG9ydCo9Cg95eWxfcmVwb3J0X3R5",
          "cGUSEwoPWVlMX1JFUE9SVF9BVVRPEAASFQoRWVlMX1JFUE9SVF9NQU5VQUwQ",
          "AUIJWgcuL2l3b3du"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::yyl_report_type), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::yyl_wuqi_report), global::yyl_wuqi_report.Parser, new[]{ "Wq", "Score" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::yyl_body_report), global::yyl_body_report.Parser, new[]{ "TzName", "TzScore", "PreTzName", "PreTzScore" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::yyl_notify), global::yyl_notify.Parser, new[]{ "HasReport", "ReportType" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::yyl_Command), global::yyl_Command.Parser, new[]{ "Modeling", "WuqiReport", "BodyReport" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum yyl_report_type {
  [pbr::OriginalName("YYL_REPORT_AUTO")] YylReportAuto = 0,
  [pbr::OriginalName("YYL_REPORT_MANUAL")] YylReportManual = 1,
}

#endregion

#region Messages
public sealed partial class yyl_wuqi_report : pb::IMessage<yyl_wuqi_report> {
  private static readonly pb::MessageParser<yyl_wuqi_report> _parser = new pb::MessageParser<yyl_wuqi_report>(() => new yyl_wuqi_report());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<yyl_wuqi_report> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::YylInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_wuqi_report() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_wuqi_report(yyl_wuqi_report other) : this() {
    wq_ = other.wq_;
    score_ = other.score_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_wuqi_report Clone() {
    return new yyl_wuqi_report(this);
  }

  /// <summary>Field number for the "wq" field.</summary>
  public const int WqFieldNumber = 1;
  private readonly static pb::ByteString WqDefaultValue = pb::ByteString.Empty;

  private pb::ByteString wq_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Wq {
    get { return wq_ ?? WqDefaultValue; }
    set {
      wq_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "wq" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasWq {
    get { return wq_ != null; }
  }
  /// <summary>Clears the value of the "wq" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearWq() {
    wq_ = null;
  }

  /// <summary>Field number for the "score" field.</summary>
  public const int ScoreFieldNumber = 2;
  private readonly static pb::ByteString ScoreDefaultValue = pb::ByteString.Empty;

  private pb::ByteString score_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Score {
    get { return score_ ?? ScoreDefaultValue; }
    set {
      score_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "score" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasScore {
    get { return score_ != null; }
  }
  /// <summary>Clears the value of the "score" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearScore() {
    score_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as yyl_wuqi_report);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(yyl_wuqi_report other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Wq != other.Wq) return false;
    if (Score != other.Score) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasWq) hash ^= Wq.GetHashCode();
    if (HasScore) hash ^= Score.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasWq) {
      output.WriteRawTag(10);
      output.WriteBytes(Wq);
    }
    if (HasScore) {
      output.WriteRawTag(18);
      output.WriteBytes(Score);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasWq) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Wq);
    }
    if (HasScore) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Score);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(yyl_wuqi_report other) {
    if (other == null) {
      return;
    }
    if (other.HasWq) {
      Wq = other.Wq;
    }
    if (other.HasScore) {
      Score = other.Score;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Wq = input.ReadBytes();
          break;
        }
        case 18: {
          Score = input.ReadBytes();
          break;
        }
      }
    }
  }

}

public sealed partial class yyl_body_report : pb::IMessage<yyl_body_report> {
  private static readonly pb::MessageParser<yyl_body_report> _parser = new pb::MessageParser<yyl_body_report>(() => new yyl_body_report());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<yyl_body_report> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::YylInfoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_body_report() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_body_report(yyl_body_report other) : this() {
    tzName_ = other.tzName_;
    tzScore_ = other.tzScore_;
    preTzName_ = other.preTzName_;
    preTzScore_ = other.preTzScore_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_body_report Clone() {
    return new yyl_body_report(this);
  }

  /// <summary>Field number for the "tz_name" field.</summary>
  public const int TzNameFieldNumber = 1;
  private readonly static pb::ByteString TzNameDefaultValue = pb::ByteString.Empty;

  private pb::ByteString tzName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString TzName {
    get { return tzName_ ?? TzNameDefaultValue; }
    set {
      tzName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "tz_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTzName {
    get { return tzName_ != null; }
  }
  /// <summary>Clears the value of the "tz_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTzName() {
    tzName_ = null;
  }

  /// <summary>Field number for the "tz_score" field.</summary>
  public const int TzScoreFieldNumber = 2;
  private readonly static pb::ByteString TzScoreDefaultValue = pb::ByteString.Empty;

  private pb::ByteString tzScore_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString TzScore {
    get { return tzScore_ ?? TzScoreDefaultValue; }
    set {
      tzScore_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "tz_score" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTzScore {
    get { return tzScore_ != null; }
  }
  /// <summary>Clears the value of the "tz_score" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTzScore() {
    tzScore_ = null;
  }

  /// <summary>Field number for the "pre_tz_name" field.</summary>
  public const int PreTzNameFieldNumber = 3;
  private readonly static pb::ByteString PreTzNameDefaultValue = pb::ByteString.Empty;

  private pb::ByteString preTzName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString PreTzName {
    get { return preTzName_ ?? PreTzNameDefaultValue; }
    set {
      preTzName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "pre_tz_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPreTzName {
    get { return preTzName_ != null; }
  }
  /// <summary>Clears the value of the "pre_tz_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPreTzName() {
    preTzName_ = null;
  }

  /// <summary>Field number for the "pre_tz_score" field.</summary>
  public const int PreTzScoreFieldNumber = 4;
  private readonly static pb::ByteString PreTzScoreDefaultValue = pb::ByteString.Empty;

  private pb::ByteString preTzScore_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString PreTzScore {
    get { return preTzScore_ ?? PreTzScoreDefaultValue; }
    set {
      preTzScore_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "pre_tz_score" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPreTzScore {
    get { return preTzScore_ != null; }
  }
  /// <summary>Clears the value of the "pre_tz_score" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPreTzScore() {
    preTzScore_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as yyl_body_report);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(yyl_body_report other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (TzName != other.TzName) return false;
    if (TzScore != other.TzScore) return false;
    if (PreTzName != other.PreTzName) return false;
    if (PreTzScore != other.PreTzScore) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTzName) hash ^= TzName.GetHashCode();
    if (HasTzScore) hash ^= TzScore.GetHashCode();
    if (HasPreTzName) hash ^= PreTzName.GetHashCode();
    if (HasPreTzScore) hash ^= PreTzScore.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTzName) {
      output.WriteRawTag(10);
      output.WriteBytes(TzName);
    }
    if (HasTzScore) {
      output.WriteRawTag(18);
      output.WriteBytes(TzScore);
    }
    if (HasPreTzName) {
      output.WriteRawTag(26);
      output.WriteBytes(PreTzName);
    }
    if (HasPreTzScore) {
      output.WriteRawTag(34);
      output.WriteBytes(PreTzScore);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTzName) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(TzName);
    }
    if (HasTzScore) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(TzScore);
    }
    if (HasPreTzName) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(PreTzName);
    }
    if (HasPreTzScore) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(PreTzScore);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(yyl_body_report other) {
    if (other == null) {
      return;
    }
    if (other.HasTzName) {
      TzName = other.TzName;
    }
    if (other.HasTzScore) {
      TzScore = other.TzScore;
    }
    if (other.HasPreTzName) {
      PreTzName = other.PreTzName;
    }
    if (other.HasPreTzScore) {
      PreTzScore = other.PreTzScore;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          TzName = input.ReadBytes();
          break;
        }
        case 18: {
          TzScore = input.ReadBytes();
          break;
        }
        case 26: {
          PreTzName = input.ReadBytes();
          break;
        }
        case 34: {
          PreTzScore = input.ReadBytes();
          break;
        }
      }
    }
  }

}

public sealed partial class yyl_notify : pb::IMessage<yyl_notify> {
  private static readonly pb::MessageParser<yyl_notify> _parser = new pb::MessageParser<yyl_notify>(() => new yyl_notify());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<yyl_notify> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::YylInfoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_notify() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_notify(yyl_notify other) : this() {
    _hasBits0 = other._hasBits0;
    hasReport_ = other.hasReport_;
    reportType_ = other.reportType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_notify Clone() {
    return new yyl_notify(this);
  }

  /// <summary>Field number for the "has_report" field.</summary>
  public const int HasReportFieldNumber = 1;
  private readonly static bool HasReportDefaultValue = false;

  private bool hasReport_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasReport {
    get { if ((_hasBits0 & 1) != 0) { return hasReport_; } else { return HasReportDefaultValue; } }
    set {
      _hasBits0 |= 1;
      hasReport_ = value;
    }
  }
  /// <summary>Gets whether the "has_report" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasHasReport {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "has_report" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearHasReport() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "report_type" field.</summary>
  public const int ReportTypeFieldNumber = 2;
  private readonly static global::yyl_report_type ReportTypeDefaultValue = global::yyl_report_type.YylReportAuto;

  private global::yyl_report_type reportType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::yyl_report_type ReportType {
    get { if ((_hasBits0 & 2) != 0) { return reportType_; } else { return ReportTypeDefaultValue; } }
    set {
      _hasBits0 |= 2;
      reportType_ = value;
    }
  }
  /// <summary>Gets whether the "report_type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasReportType {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "report_type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearReportType() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as yyl_notify);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(yyl_notify other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (HasReport != other.HasReport) return false;
    if (ReportType != other.ReportType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasHasReport) hash ^= HasReport.GetHashCode();
    if (HasReportType) hash ^= ReportType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasHasReport) {
      output.WriteRawTag(8);
      output.WriteBool(HasReport);
    }
    if (HasReportType) {
      output.WriteRawTag(16);
      output.WriteEnum((int) ReportType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasHasReport) {
      size += 1 + 1;
    }
    if (HasReportType) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReportType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(yyl_notify other) {
    if (other == null) {
      return;
    }
    if (other.HasHasReport) {
      HasReport = other.HasReport;
    }
    if (other.HasReportType) {
      ReportType = other.ReportType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          HasReport = input.ReadBool();
          break;
        }
        case 16: {
          ReportType = (global::yyl_report_type) input.ReadEnum();
          break;
        }
      }
    }
  }

}

public sealed partial class yyl_Command : pb::IMessage<yyl_Command> {
  private static readonly pb::MessageParser<yyl_Command> _parser = new pb::MessageParser<yyl_Command>(() => new yyl_Command());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<yyl_Command> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::YylInfoReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_Command() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_Command(yyl_Command other) : this() {
    _hasBits0 = other._hasBits0;
    modeling_ = other.modeling_;
    wuqiReport_ = other.HasWuqiReport ? other.wuqiReport_.Clone() : null;
    bodyReport_ = other.HasBodyReport ? other.bodyReport_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public yyl_Command Clone() {
    return new yyl_Command(this);
  }

  /// <summary>Field number for the "modeling" field.</summary>
  public const int ModelingFieldNumber = 1;
  private readonly static bool ModelingDefaultValue = false;

  private bool modeling_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Modeling {
    get { if ((_hasBits0 & 1) != 0) { return modeling_; } else { return ModelingDefaultValue; } }
    set {
      _hasBits0 |= 1;
      modeling_ = value;
    }
  }
  /// <summary>Gets whether the "modeling" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasModeling {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "modeling" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearModeling() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "wuqi_report" field.</summary>
  public const int WuqiReportFieldNumber = 4;
  private global::yyl_wuqi_report wuqiReport_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::yyl_wuqi_report WuqiReport {
    get { return wuqiReport_; }
    set {
      wuqiReport_ = value;
    }
  }
  /// <summary>Gets whether the wuqi_report field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasWuqiReport {
    get { return wuqiReport_ != null; }
  }
  /// <summary>Clears the value of the wuqi_report field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearWuqiReport() {
    wuqiReport_ = null;
  }

  /// <summary>Field number for the "body_report" field.</summary>
  public const int BodyReportFieldNumber = 5;
  private global::yyl_body_report bodyReport_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::yyl_body_report BodyReport {
    get { return bodyReport_; }
    set {
      bodyReport_ = value;
    }
  }
  /// <summary>Gets whether the body_report field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBodyReport {
    get { return bodyReport_ != null; }
  }
  /// <summary>Clears the value of the body_report field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBodyReport() {
    bodyReport_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as yyl_Command);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(yyl_Command other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Modeling != other.Modeling) return false;
    if (!object.Equals(WuqiReport, other.WuqiReport)) return false;
    if (!object.Equals(BodyReport, other.BodyReport)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasModeling) hash ^= Modeling.GetHashCode();
    if (HasWuqiReport) hash ^= WuqiReport.GetHashCode();
    if (HasBodyReport) hash ^= BodyReport.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasModeling) {
      output.WriteRawTag(8);
      output.WriteBool(Modeling);
    }
    if (HasWuqiReport) {
      output.WriteRawTag(34);
      output.WriteMessage(WuqiReport);
    }
    if (HasBodyReport) {
      output.WriteRawTag(42);
      output.WriteMessage(BodyReport);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasModeling) {
      size += 1 + 1;
    }
    if (HasWuqiReport) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(WuqiReport);
    }
    if (HasBodyReport) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BodyReport);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(yyl_Command other) {
    if (other == null) {
      return;
    }
    if (other.HasModeling) {
      Modeling = other.Modeling;
    }
    if (other.HasWuqiReport) {
      if (!HasWuqiReport) {
        WuqiReport = new global::yyl_wuqi_report();
      }
      WuqiReport.MergeFrom(other.WuqiReport);
    }
    if (other.HasBodyReport) {
      if (!HasBodyReport) {
        BodyReport = new global::yyl_body_report();
      }
      BodyReport.MergeFrom(other.BodyReport);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Modeling = input.ReadBool();
          break;
        }
        case 34: {
          if (!HasWuqiReport) {
            WuqiReport = new global::yyl_wuqi_report();
          }
          input.ReadMessage(WuqiReport);
          break;
        }
        case 42: {
          if (!HasBodyReport) {
            BodyReport = new global::yyl_body_report();
          }
          input.ReadMessage(BodyReport);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
