// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Gyroscope_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Gyroscope_data.proto</summary>
public static partial class GyroscopeDataReflection {

  #region Descriptor
  /// <summary>File descriptor for Gyroscope_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GyroscopeDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRHeXJvc2NvcGVfZGF0YS5wcm90bxoTcmVhbHRpbWVfZGF0YS5wcm90byKK",
          "AQoMSGlzR3lyb3Njb3BlEh0KCnRpbWVfc3RhbXAYASACKAsyCS5EYXRlVGlt",
          "ZRIcChRHeXJvc2NvcGVfZGF0YV9jb3VudBgCIAIoBxITCgtHeXJvc2NvcGVf",
          "eBgDIAIoDBITCgtHeXJvc2NvcGVfeRgEIAIoDBITCgtHeXJvc2NvcGVfehgF",
          "IAIoDEIJWgcuL2l3b3du"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HisGyroscope), global::HisGyroscope.Parser, new[]{ "TimeStamp", "GyroscopeDataCount", "GyroscopeX", "GyroscopeY", "GyroscopeZ" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HisGyroscope : pb::IMessage<HisGyroscope> {
  private static readonly pb::MessageParser<HisGyroscope> _parser = new pb::MessageParser<HisGyroscope>(() => new HisGyroscope());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisGyroscope> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GyroscopeDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisGyroscope() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisGyroscope(HisGyroscope other) : this() {
    _hasBits0 = other._hasBits0;
    timeStamp_ = other.HasTimeStamp ? other.timeStamp_.Clone() : null;
    gyroscopeDataCount_ = other.gyroscopeDataCount_;
    gyroscopeX_ = other.gyroscopeX_;
    gyroscopeY_ = other.gyroscopeY_;
    gyroscopeZ_ = other.gyroscopeZ_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisGyroscope Clone() {
    return new HisGyroscope(this);
  }

  /// <summary>Field number for the "time_stamp" field.</summary>
  public const int TimeStampFieldNumber = 1;
  private global::DateTime timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DateTime TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the time_stamp field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTimeStamp {
    get { return timeStamp_ != null; }
  }
  /// <summary>Clears the value of the time_stamp field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTimeStamp() {
    timeStamp_ = null;
  }

  /// <summary>Field number for the "Gyroscope_data_count" field.</summary>
  public const int GyroscopeDataCountFieldNumber = 2;
  private readonly static uint GyroscopeDataCountDefaultValue = 0;

  private uint gyroscopeDataCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint GyroscopeDataCount {
    get { if ((_hasBits0 & 1) != 0) { return gyroscopeDataCount_; } else { return GyroscopeDataCountDefaultValue; } }
    set {
      _hasBits0 |= 1;
      gyroscopeDataCount_ = value;
    }
  }
  /// <summary>Gets whether the "Gyroscope_data_count" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGyroscopeDataCount {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "Gyroscope_data_count" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGyroscopeDataCount() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "Gyroscope_x" field.</summary>
  public const int GyroscopeXFieldNumber = 3;
  private readonly static pb::ByteString GyroscopeXDefaultValue = pb::ByteString.Empty;

  private pb::ByteString gyroscopeX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString GyroscopeX {
    get { return gyroscopeX_ ?? GyroscopeXDefaultValue; }
    set {
      gyroscopeX_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Gyroscope_x" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGyroscopeX {
    get { return gyroscopeX_ != null; }
  }
  /// <summary>Clears the value of the "Gyroscope_x" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGyroscopeX() {
    gyroscopeX_ = null;
  }

  /// <summary>Field number for the "Gyroscope_y" field.</summary>
  public const int GyroscopeYFieldNumber = 4;
  private readonly static pb::ByteString GyroscopeYDefaultValue = pb::ByteString.Empty;

  private pb::ByteString gyroscopeY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString GyroscopeY {
    get { return gyroscopeY_ ?? GyroscopeYDefaultValue; }
    set {
      gyroscopeY_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Gyroscope_y" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGyroscopeY {
    get { return gyroscopeY_ != null; }
  }
  /// <summary>Clears the value of the "Gyroscope_y" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGyroscopeY() {
    gyroscopeY_ = null;
  }

  /// <summary>Field number for the "Gyroscope_z" field.</summary>
  public const int GyroscopeZFieldNumber = 5;
  private readonly static pb::ByteString GyroscopeZDefaultValue = pb::ByteString.Empty;

  private pb::ByteString gyroscopeZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString GyroscopeZ {
    get { return gyroscopeZ_ ?? GyroscopeZDefaultValue; }
    set {
      gyroscopeZ_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Gyroscope_z" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGyroscopeZ {
    get { return gyroscopeZ_ != null; }
  }
  /// <summary>Clears the value of the "Gyroscope_z" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGyroscopeZ() {
    gyroscopeZ_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisGyroscope);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisGyroscope other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
    if (GyroscopeDataCount != other.GyroscopeDataCount) return false;
    if (GyroscopeX != other.GyroscopeX) return false;
    if (GyroscopeY != other.GyroscopeY) return false;
    if (GyroscopeZ != other.GyroscopeZ) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    if (HasGyroscopeDataCount) hash ^= GyroscopeDataCount.GetHashCode();
    if (HasGyroscopeX) hash ^= GyroscopeX.GetHashCode();
    if (HasGyroscopeY) hash ^= GyroscopeY.GetHashCode();
    if (HasGyroscopeZ) hash ^= GyroscopeZ.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasTimeStamp) {
      output.WriteRawTag(10);
      output.WriteMessage(TimeStamp);
    }
    if (HasGyroscopeDataCount) {
      output.WriteRawTag(21);
      output.WriteFixed32(GyroscopeDataCount);
    }
    if (HasGyroscopeX) {
      output.WriteRawTag(26);
      output.WriteBytes(GyroscopeX);
    }
    if (HasGyroscopeY) {
      output.WriteRawTag(34);
      output.WriteBytes(GyroscopeY);
    }
    if (HasGyroscopeZ) {
      output.WriteRawTag(42);
      output.WriteBytes(GyroscopeZ);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
    }
    if (HasGyroscopeDataCount) {
      size += 1 + 4;
    }
    if (HasGyroscopeX) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(GyroscopeX);
    }
    if (HasGyroscopeY) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(GyroscopeY);
    }
    if (HasGyroscopeZ) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(GyroscopeZ);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisGyroscope other) {
    if (other == null) {
      return;
    }
    if (other.HasTimeStamp) {
      if (!HasTimeStamp) {
        TimeStamp = new global::DateTime();
      }
      TimeStamp.MergeFrom(other.TimeStamp);
    }
    if (other.HasGyroscopeDataCount) {
      GyroscopeDataCount = other.GyroscopeDataCount;
    }
    if (other.HasGyroscopeX) {
      GyroscopeX = other.GyroscopeX;
    }
    if (other.HasGyroscopeY) {
      GyroscopeY = other.GyroscopeY;
    }
    if (other.HasGyroscopeZ) {
      GyroscopeZ = other.GyroscopeZ;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasTimeStamp) {
            TimeStamp = new global::DateTime();
          }
          input.ReadMessage(TimeStamp);
          break;
        }
        case 21: {
          GyroscopeDataCount = input.ReadFixed32();
          break;
        }
        case 26: {
          GyroscopeX = input.ReadBytes();
          break;
        }
        case 34: {
          GyroscopeY = input.ReadBytes();
          break;
        }
        case 42: {
          GyroscopeZ = input.ReadBytes();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
