// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: his_encrypt_rri_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from his_encrypt_rri_data.proto</summary>
public static partial class HisEncryptRriDataReflection {

  #region Descriptor
  /// <summary>File descriptor for his_encrypt_rri_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HisEncryptRriDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpoaXNfZW5jcnlwdF9ycmlfZGF0YS5wcm90bxoTcmVhbHRpbWVfZGF0YS5w",
          "cm90bxoSaGlzX3JyaV9kYXRhLnByb3RvIlAKDUhpc1JSSUVuY3J5cHQSHwoK",
          "cnJpZW5jcnlwdBgBIAIoCzILLkhpc0RhdGFSUkkSDgoGUmFuZG9tGAIgAigM",
          "Eg4KBkJsZU1hYxgDIAIoDCJMChFIaXNEYXRhUlJJRW5jcnlwdBIfCgdoaXNf",
          "cnJpGAEgAigLMg4uSGlzUlJJRW5jcnlwdBIWCg5zaWduYXR1cmVfZGF0YRgC",
          "IAIoDEIJWgcuL2l3b3du"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RealtimeDataReflection.Descriptor, global::HisRriDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HisRRIEncrypt), global::HisRRIEncrypt.Parser, new[]{ "Rriencrypt", "Random", "BleMac" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HisDataRRIEncrypt), global::HisDataRRIEncrypt.Parser, new[]{ "HisRri", "SignatureData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HisRRIEncrypt : pb::IMessage<HisRRIEncrypt> {
  private static readonly pb::MessageParser<HisRRIEncrypt> _parser = new pb::MessageParser<HisRRIEncrypt>(() => new HisRRIEncrypt());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisRRIEncrypt> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisEncryptRriDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisRRIEncrypt() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisRRIEncrypt(HisRRIEncrypt other) : this() {
    rriencrypt_ = other.HasRriencrypt ? other.rriencrypt_.Clone() : null;
    random_ = other.random_;
    bleMac_ = other.bleMac_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisRRIEncrypt Clone() {
    return new HisRRIEncrypt(this);
  }

  /// <summary>Field number for the "rriencrypt" field.</summary>
  public const int RriencryptFieldNumber = 1;
  private global::HisDataRRI rriencrypt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::HisDataRRI Rriencrypt {
    get { return rriencrypt_; }
    set {
      rriencrypt_ = value;
    }
  }
  /// <summary>Gets whether the rriencrypt field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRriencrypt {
    get { return rriencrypt_ != null; }
  }
  /// <summary>Clears the value of the rriencrypt field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRriencrypt() {
    rriencrypt_ = null;
  }

  /// <summary>Field number for the "Random" field.</summary>
  public const int RandomFieldNumber = 2;
  private readonly static pb::ByteString RandomDefaultValue = pb::ByteString.Empty;

  private pb::ByteString random_;
  /// <summary>
  ///random number 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Random {
    get { return random_ ?? RandomDefaultValue; }
    set {
      random_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Random" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRandom {
    get { return random_ != null; }
  }
  /// <summary>Clears the value of the "Random" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRandom() {
    random_ = null;
  }

  /// <summary>Field number for the "BleMac" field.</summary>
  public const int BleMacFieldNumber = 3;
  private readonly static pb::ByteString BleMacDefaultValue = pb::ByteString.Empty;

  private pb::ByteString bleMac_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString BleMac {
    get { return bleMac_ ?? BleMacDefaultValue; }
    set {
      bleMac_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "BleMac" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBleMac {
    get { return bleMac_ != null; }
  }
  /// <summary>Clears the value of the "BleMac" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBleMac() {
    bleMac_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisRRIEncrypt);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisRRIEncrypt other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Rriencrypt, other.Rriencrypt)) return false;
    if (Random != other.Random) return false;
    if (BleMac != other.BleMac) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasRriencrypt) hash ^= Rriencrypt.GetHashCode();
    if (HasRandom) hash ^= Random.GetHashCode();
    if (HasBleMac) hash ^= BleMac.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasRriencrypt) {
      output.WriteRawTag(10);
      output.WriteMessage(Rriencrypt);
    }
    if (HasRandom) {
      output.WriteRawTag(18);
      output.WriteBytes(Random);
    }
    if (HasBleMac) {
      output.WriteRawTag(26);
      output.WriteBytes(BleMac);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasRriencrypt) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rriencrypt);
    }
    if (HasRandom) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Random);
    }
    if (HasBleMac) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(BleMac);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisRRIEncrypt other) {
    if (other == null) {
      return;
    }
    if (other.HasRriencrypt) {
      if (!HasRriencrypt) {
        Rriencrypt = new global::HisDataRRI();
      }
      Rriencrypt.MergeFrom(other.Rriencrypt);
    }
    if (other.HasRandom) {
      Random = other.Random;
    }
    if (other.HasBleMac) {
      BleMac = other.BleMac;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasRriencrypt) {
            Rriencrypt = new global::HisDataRRI();
          }
          input.ReadMessage(Rriencrypt);
          break;
        }
        case 18: {
          Random = input.ReadBytes();
          break;
        }
        case 26: {
          BleMac = input.ReadBytes();
          break;
        }
      }
    }
  }

}

public sealed partial class HisDataRRIEncrypt : pb::IMessage<HisDataRRIEncrypt> {
  private static readonly pb::MessageParser<HisDataRRIEncrypt> _parser = new pb::MessageParser<HisDataRRIEncrypt>(() => new HisDataRRIEncrypt());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<HisDataRRIEncrypt> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HisEncryptRriDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataRRIEncrypt() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataRRIEncrypt(HisDataRRIEncrypt other) : this() {
    hisRri_ = other.HasHisRri ? other.hisRri_.Clone() : null;
    signatureData_ = other.signatureData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public HisDataRRIEncrypt Clone() {
    return new HisDataRRIEncrypt(this);
  }

  /// <summary>Field number for the "his_rri" field.</summary>
  public const int HisRriFieldNumber = 1;
  private global::HisRRIEncrypt hisRri_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::HisRRIEncrypt HisRri {
    get { return hisRri_; }
    set {
      hisRri_ = value;
    }
  }
  /// <summary>Gets whether the his_rri field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasHisRri {
    get { return hisRri_ != null; }
  }
  /// <summary>Clears the value of the his_rri field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearHisRri() {
    hisRri_ = null;
  }

  /// <summary>Field number for the "signature_data" field.</summary>
  public const int SignatureDataFieldNumber = 2;
  private readonly static pb::ByteString SignatureDataDefaultValue = pb::ByteString.Empty;

  private pb::ByteString signatureData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString SignatureData {
    get { return signatureData_ ?? SignatureDataDefaultValue; }
    set {
      signatureData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "signature_data" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSignatureData {
    get { return signatureData_ != null; }
  }
  /// <summary>Clears the value of the "signature_data" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSignatureData() {
    signatureData_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as HisDataRRIEncrypt);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(HisDataRRIEncrypt other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(HisRri, other.HisRri)) return false;
    if (SignatureData != other.SignatureData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasHisRri) hash ^= HisRri.GetHashCode();
    if (HasSignatureData) hash ^= SignatureData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasHisRri) {
      output.WriteRawTag(10);
      output.WriteMessage(HisRri);
    }
    if (HasSignatureData) {
      output.WriteRawTag(18);
      output.WriteBytes(SignatureData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasHisRri) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(HisRri);
    }
    if (HasSignatureData) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(SignatureData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(HisDataRRIEncrypt other) {
    if (other == null) {
      return;
    }
    if (other.HasHisRri) {
      if (!HasHisRri) {
        HisRri = new global::HisRRIEncrypt();
      }
      HisRri.MergeFrom(other.HisRri);
    }
    if (other.HasSignatureData) {
      SignatureData = other.SignatureData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (!HasHisRri) {
            HisRri = new global::HisRRIEncrypt();
          }
          input.ReadMessage(HisRri);
          break;
        }
        case 18: {
          SignatureData = input.ReadBytes();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
